### ISSUE TITLE
support for VolumeSnapshot in 1.17

### ISSUE THREAD

**Issue by ajaykmis** [kubernetes-client/java#1131]
I am trying to use VolumeSnapshotting feature in kubernetes which is supported in beta in 1.17.

https://kubernetes.io/docs/concepts/storage/volume-snapshots/

But looking through the client, I didn't find any support for the classes "API Objects VolumeSnapshot, VolumeSnapshotContent, and VolumeSnapshotClass are CRDs" in this client.

is there a plan to add support for these in fabric client? or is there another way I can use these from the Java client?

**Comment by brendandburns** [comment]
since the snapshot objects are CRDs (Custom Resource Definitions) they are not in the Swagger document that is used to create this library.

You can use the CustomObjectsAPI (example: https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/apis/CustomObjectsApi.java)

You will need to either hand code the API objects

Or you can generate your own objects for the CRDs (assuming that the Swagger is published somewhere) using the instructions here:

**Comment by yue9944882** [comment]
> You can use the CustomObjectsAPI (example: https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/apis/CustomObjectsApi.java)

the snapshots CRDs are defined unstructured, hence we're not able to generate models for them.. but you're free to the `CustomObjectApi` to manipulate the resources

https://github.com/kubernetes-csi/external-snapshotter/blob/d5da3c1e527cd356696300222ebd8bf728971ae4/cmd/csi-snapshotter/create_crd.go#L28-L100

**Comment by brendandburns** [comment]
Closing this since we have #1132 and it seems that the question is answered.  @ajaykmis if you get this going and want to submit a utility class for this we'd be happy to have it (or an example)
