### ISSUE TITLE
Prebuilt Model Classes from CRDs of Popular Project

### ISSUE THREAD

**Issue by simingweng** [kubernetes-client/java#1132]
Based on the [discussion](https://kubernetes.slack.com/archives/C76GB48RK/p1595947869394500?thread_ts=1595941682.386300&cid=C76GB48RK) with @yue9944882 on Slack, it will be beneficial to the Kubernetes Java Client user community if there's pre-built Java model classes generated from CRDs of some popular projects, such as:

- Prometheus Operator
- Cert Manager
- Istio
- Helm Operator

With these model classes readily available as maven dependencies, application can be created in Java to interact with those operators with type safety out of the box.

Their versions should track the upstream project release versions.

So, the suggestion is to have a dedicated fold, for example, `client-java-contrib`, to keep those pre-built model classes. An automation shall be set up according to https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md, so that every time the upstream project has a new release, it becomes easier to generate model classes.

**Comment by brendandburns** [comment]
This seems good to me, but let's have a dedicated sub-folder per project (e.g

`./client-java-contrib/src/main/.../helm/...`
`./client-java-contrib/src/main/.../prometheus/...`

There was just an issue requesting support for Volume Snapshots (#1131) so let's generate those too.

Thanks!

**Comment by yue9944882** [comment]
thanks for starting this! i also have a couple ideas in mind in terms of incubating a new module holding those pre-built commonly-used models from CRD:

- Leveraging https://github.com/kubernetes-sigs/kind to automate/homogenize the model generation process: the current model generation guide requires us to have a kubernetes cluster greater than v1.16.0, which can bring unnecessary cost to the users. we used to pack the generation scripts into a container image before https://github.com/kubernetes-client/java/commit/97eb1ab6b79c91ba5f1ac7d42c03b0552d94f6b1#diff-d633a48e20befcc8f98d526bdcbb859c. i'd expect a new container image composes (kind + generation scripts) to simplify the process further.

- Tracking CRD model updates: the tough part is to maintain the models in a continuous way.. i suppose in the short term we can start by updating the models according to the feedbacks/complaints from the model consumers, but the bound is fragile.. 

- CRD reviewing: additionally the model generation has a requirement on CRD manifests:
  1. the CRD has to enable the [pruning feature](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#preserving-unknown-fields), which is by default disable for v1beta1 CRD api but enable for v1 CRD api.. sadly most of the CRDs are written in v1beta1 for now 
  2. the CRD's schema has to be correct/valid, otherwise a violation condition will be attached onto its status and meanwhile it will fallback to unstructured regardless of all of its schema definitions..

**Comment by simingweng** [comment]
@brendandburns do we want to have a single sub module `client-java-contrib` to house all of the models classes generated from different OSS projects? or would it be better to have dedicated sub modules under `client-java-contrib`, such as `./client-java-contrib/cert-manager/src/main/...` for `certificate manager` only, and `./client-java-contrib/prometheus-operator/src/main/...` for `prometheus operator` only. That way, we can publish different maven dependencies for each project, and user is able to choose whichever one they need.

Also, each published maven dependency can have its own version, which ideally shall track the upstream project release version.
