### ISSUE TITLE
how Exec get stdout and stderr together ?

### ISSUE THREAD

**Issue by jerry-sc** [kubernetes-client/java#1202]
I want use Exec to execute a command, like `ls fileA fileB`. When fileA is exist, fileB is not exist. So I use proc.getInputStream() and proc.getErrorStream() to receive the result. But it failed with `java.lang.IllegalStateException`.  Can anyone show me an example how to get stdout and stderr correctly ?

**Comment by brendandburns** [comment]
That exception is likely occurring because you're trying to get the stream before the web socket is fully connected.

What does your code look like? have you looked at the `ExecExample` here:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/ExecExample.java

**Comment by brendandburns** [comment]
Closing this issue due to lack of additional information. Please use the `/reopen` command if you need further assistance.

**Comment by kumars17** [comment]
Not sure if you managed to get a fix for this. I am hitting same issue. Example https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/ExecExample.java doesn't read stderr. Is there any example where both stdout and stderr output is collected by the client?
