### ISSUE TITLE
APIServer example

### ISSUE THREAD

**Issue by mattmoor** [kubernetes-client/java#121]
Are there any examples that extend the APIServer in Java?

**Comment by brendandburns** [comment]
Do you mean using `CustomResourceDefinition`?

If so, there is an example here:

https://github.com/metaparticle-io/container-lib/blob/master/elector/src/main/java/io/metaparticle/containerlib/elector/KubernetesStorage.java

If you mean via aggregated APIs, then no, I don't know of an example.  I'm not even sure this library is sufficient, since you can make the client calls, but it won't help you write the server since it's client-only.

**Comment by mattmoor** [comment]
Yep, that's exactly what I'd like to see for more languages :-/

**Comment by brendandburns** [comment]
Can you clarify what "that" points to :)

**Comment by mattmoor** [comment]
LOL sorry.  [that](https://github.com/kubernetes/sample-apiserver). :)

I think we probably also need something like `apiserver-builder` for more languages (it is magical, kudos @pwittrock).

**Comment by brendandburns** [comment]
Yeah that's out of scope for this library, but probably a good idea. But there are lots of projects out there to create language servers from swagger specs...

--brendan

________________________________

**Comment by brendandburns** [comment]
Closing because out of scope.
