### ISSUE TITLE
Creating a pod based on the example never succeeded

### ISSUE THREAD

**Issue by Sherlock-Harden** [kubernetes-client/java#1358]
When I use
~~~java
GenericKubernetesApi<V1Pod, V1PodList> podClient =  new GenericKubernetesApi<>(V1 Pod.class , V1 PodList.class , "", "v1", "pods", apiClient);
podClient.create (pod)；
~~~
to create a pod, it always fails
Found in the source code CustomObjectsApi.class The restful URL starts with / apis, 

but the URL given by the official website is /api/v1/namespaces/{namespace}/pods

<img width="1427" alt="截屏2020-11-02 17 22 09" src="https://user-images.githubusercontent.com/55943281/97851612-8c097d80-1d30-11eb-93d9-36245c418271.png">

**Comment by yue9944882** [comment]
> Found in the source code CustomObjectsApi.class The restful URL starts with / apis,
> but the URL given by the official website is /api/v1/namespaces/{namespace}/pods

the generic api will use the corev1api if the passing apiGroup is empty string (""), which is correct in your source code.
https://github.com/kubernetes-client/java/blob/2ebac6dd9aece8509ee39b6aa30f2ce5e871fc1e/util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java#L762-L771

can you add `.throwsApiException().getObject()` to ur create call so that expcetion or failure can be handled?

https://github.com/kubernetes-client/java/blob/2ebac6dd9aece8509ee39b6aa30f2ce5e871fc1e/examples/src/main/java/io/kubernetes/client/examples/GenericClientExample.java#L42

**Comment by brendandburns** [comment]
fwiw, you probably don't want to use the GenericAPI for creating Pods anyway, you should use the CoreV1Api
