### ISSUE TITLE
Why is the value of containerPort in V1ControllerRevision float?

### ISSUE THREAD

**Issue by fomin-zhu** [kubernetes-client/java#1403]
![image](https://user-images.githubusercontent.com/15045711/100508553-aeb07a00-31a8-11eb-8240-24a0c1e41a74.png)

**Comment by brendandburns** [comment]
The `data` field in `V1ControllerRevision` is unstructured data (it's `Object` in the class). That means that it has the default JSON object representation and in JSON/Javascript all numbers are floats.

Closing this issue, since the question is answered. Please use `/reopen` if you need further assistance.
