### ISSUE TITLE
feat(checksums): please provide checksums.txt

### ISSUE THREAD

**Issue by noelmcloughlin** [kubernetes-client/java#1446]
Can you provide a checksums.txt with releases?

**Comment by brendandburns** [comment]
The releases are all done through Maven which as far as I know already includes checksums.

Can you clarify what you are looking for?

**Comment by noelmcloughlin** [comment]
GitHub releases often provide checksums Assets - either "checksums.txt" or ".sha256" files for each asset depending on how the release assets are generated here: https://github.com/kubernetes-client/java/releases/tag/client-java-parent-10.0.0

**Comment by brendandburns** [comment]
We don't provide any assets there except the ones that Github automatically creates (the zipfile of the source at a specific commit)

I don't know if there is a way to remove those, but I will see, because I don't think that is the way we want to distribute the library.

Our recommended way of consuming the library is via maven.

**Comment by brendandburns** [comment]
Update: I looked at the 'edit the release' and there's no way to remove those zipfiles.

I'm going to close this issue, since I don't think that us providing checksums for zip files that GitHub creates adds much value or trust (and we'd prefer we could opt out of those zipfiles anyway)

**Comment by noelmcloughlin** [comment]
Please don't remove the GitHub assets. Stay compliant with license.  It is a convention in cloud-native CNCF projects and Apache 2.0 license to deliver the source and I'm consuming those assets as the end-user.
