### ISSUE TITLE
Is there an example for webhook. Such as  MutatingWebhook

### ISSUE THREAD

**Issue by WywTed** [kubernetes-client/java#1451]
/question

**Comment by brendandburns** [comment]
No there's no example for that, but you should be able to use the docs here:

https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

To create one.

The relevant class is here:
https://github.com/kubernetes-client/java/blob/517ddc592d0a2347016bbb4e5f4122d38c4c1e66/kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1MutatingWebhook.java

If you do create an example, we'd welcome a PR.

Closing this issue since the question is answered.
