### ISSUE TITLE
copyFileToPod method not working in 11.0.0

### ISSUE THREAD

**Issue by miguelruizdev** [kubernetes-client/java#1489]
Hello team!
I found a problem with the Kubernetes java client while updating from `10.0.0` to `11.0.0`
This call does not work anymore copy.copyFileToPod(namespace, pod, container, src, destPath) here: https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/Copy.java#L381
the file is not copied and I see this error in the logs:
```
i.k.client.util.WebSocketStreamHandler   : Error on flush
java.io.IOException: Socket is closed!
	at io.kubernetes.client.util.WebSocketStreamHandler$WebSocketOutputStream.flush(WebSocketStreamHandler.java:221)
	at io.kubernetes.client.util.WebSocketStreamHandler.close(WebSocketStreamHandler.java:136)
	at io.kubernetes.client.Exec$ExecProcess$1.close(Exec.java:542)
	at io.kubernetes.client.Exec$ExecProcess$1.handleMessage(Exec.java:508)
	at io.kubernetes.client.util.WebSocketStreamHandler.bytesMessage(WebSocketStreamHandler.java:75)
	at io.kubernetes.client.util.WebSockets$Listener.onMessage(WebSockets.java:142)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:326)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:221)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.io.IOException: Copy failed: 137
```
Environment and Kubernetes version used: eks 1.18.9
Thanks in advance!

**Comment by brendandburns** [comment]
I don't think there are many changes to this code between 10.0.x and 11.0.0

This error looks like the socket was closed somewhere in the stream (e.g. the tar command failing inside your container)

**Comment by miguelruizdev** [comment]
I can see all the async methods added in `11.0.0`.

After trying several times, the error comes up with the change of the version of the library.
I can even add a workaround to my project, but the socket error consistently happens when upgrading from `10.0.0` to `11.0.0`

**Comment by brendandburns** [comment]
I'll see if I can repro.

**Comment by sarveshkaushal** [comment]
I can repro this too. After adding ProcessFuture to Copy class, we are trying to return future object with already used process object.

**Comment by sarveshkaushal** [comment]
Looked at it a bit more. get() method of ProcessFuture inner class has some statements that are creating problems. `proc.waitFor()` puts the current thread in indefinite waiting state as the underlying socket stream never closes/ends(I think). Skipping the waitFor() should fix this but it might break other methods.

**Comment by rjeberhard** [comment]
This does look like the same issue as #1524. I'm going to try and create a smaller reproducer for this today, but I did notice that the client is trying to write a close message when it finds that the connection is already closed. This may be something like a timing issue in that the client fails to parse a close message already received from the server before it tries to send its own close message. 

Our QA team is saying that they've seen this same failure when using Exec prior to client version 11.0.0 and they worked around it by using a call to `kubectl exec` in its place.

**Comment by rjeberhard** [comment]
I'm also able to reproduce this with a very simple CopyToPod main class, but where `kubectl cp` succeeds. @sarveshkaushal  or @brendandburns, are you aware of any one already working on a fix? If not, I can work on a proposal.

**Comment by sarveshkaushal** [comment]
@rjeberhard - I put a temporary fix by commenting the part `proc.destroy()` inside `get()` method of `ProcessFuture` class to make this work. But there even after this fix, The exit code received from the process is -1 even though the actual file gets copied to the pod. Also this might fail other async methods which need to be tested or we can just put `proc.waitFor()` conditionally there. Need @brendandburns  here to comment on this.

**Comment by rjeberhard** [comment]
Okay, we'll see what Brendan says. Based on this last stack, I'm adjusting my hypothesis... The destroy() call is closing all streams, but the data has not yet been flushed even though the waitFor() indicates that the client has received the process exit code from the server.

**Comment by rjeberhard** [comment]
In the current flow, the stdin stream is closed after the file data is written; however, the web socket session hangs because the client never sends a CLOSE message. I believe this is why Sarvesh was suggested possibly removing the waitFor() and moving on to the destory(), which does close the WebSocketStreamHandler instance triggering the CLOSE message.

However, I agree that it is incorrect to change get() to not do the waitFor().

@brendandburns, would it be appropriate for the Exec to send a CLOSE message when the stdin stream is closed?

Note: with the current code, the Copy call hangs at the waitFor(). If I Ctrl-C the Java process then I do see the file being copied to the pod appear in the container's file system.

Note 2: there seems to be a second problem with very large files. If I try and copy a 512MB file, then only approximately the first 12MB's appear following the Ctrl-C.

I'm going to experiment with sending the CLOSE message as described above.

**Comment by rjeberhard** [comment]
My experiments so far have not been successful. I think I need someone access to someone with some more web sockets expertise. When I have the client send the standard web sockets graceful termination message following the close of the input stream, then I never see the channel 3 message with the exit code.

I created a similar reproducer with that other popular Java client for Kubernetes and was able to copy files to a pod successfully: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/UploadFileToPod.java. 

I don't plan on switching clients, but this does tell me that this pattern does work assuming we can find where this client is driving the web socket layer differently than what the other client is doing.

**Comment by rjeberhard** [comment]
Okay, so 🤦 ... That client just doesn't bother to check the exit status. In their pattern, they have a custom WebSocketListener for each use case: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadWebSocketListener.java.

This is similar to @sarveshkaushal's proposal to remove the waitFor(), but I think instead it needs to be a general argument to building the Exec, such as isShouldWaitForExitCode() and then, if false, assume 0 rather than -1.

**Comment by rjeberhard** [comment]
I have copyFileToPod() working and I can confirm that, as @sarveshkaushal suggested, the basic fix is not waiting for the peer to send the close message as it is the client side that signals that the copy is done in this use case.

One annoyance is that JVM doesn't exit after the main class exits because there are several non-daemon threads. Do either of you know a way to configure this or is it expected that I call a shutdown method?

**Comment by sarveshkaushal** [comment]
@rjeberhard As far as I know even in the old implementation the JVM doesn't exit. It might have been intentional. I am not sure.

**Comment by aliyueshuo** [comment]
I can repro this too. so i turn to use 10.0.1 version and its ok
