### ISSUE TITLE
Unexpected unknown resource type exception when calling KubectlDrain

### ISSUE THREAD

**Issue by henrymollman** [kubernetes-client/java#1565]
Hello, I recently updated to version 11 after experiencing a NullPointerException on version 10 when calling the KubectlDrain method, `Kubectl.drain().ignoreDaemonSets().apiClient(apiClient).name(name).execute();`, but now I am seeing another error:

```
io.kubernetes.client.extended.kubectl.exception.KubectlException: Unexpected unknown resource type: class io.kubernetes.client.openapi.models.V1Node
\tat io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.getGenericApi(Kubectl.java:256)
\tat io.kubernetes.client.extended.kubectl.Kubectl$ResourceBuilder.getGenericApi(Kubectl.java:297)
\tat io.kubernetes.client.extended.kubectl.KubectlCordon.performCordon(KubectlCordon.java:44)
\tat io.kubernetes.client.extended.kubectl.KubectlDrain.doDrain(KubectlDrain.java:63)
\tat io.kubernetes.client.extended.kubectl.KubectlDrain.execute(KubectlDrain.java:55)
```

I experience this error on a container built from an Ubuntu base image with Java openjdk version 1.8.0_252, but not on a Mac development machine running the same application.

Please let me know if I can provide any more information. Thank you.

**Comment by brendandburns** [comment]
The ModelMapper isn't loading correctly. Specifically this code here:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/ModelMapper.java#L74

Is not running, or it is running in a different context.

You can always initialize it yourself with ModelMapper.initModelMap() but it would be interesting to understand why this is happening, can you supply more details of your setup? e.g. are you running under tomcat? Multiple class loaders?

**Comment by yue9944882** [comment]
this should be fixed by https://github.com/kubernetes-client/java/pull/1369, published in 10.0.1,9.0.2,11.0.0

**Comment by henrymollman** [comment]
The application is a spring boot application, running with embedded Tomcat. Under version 10.0.0 I experienced the NullPointerException in [#1362](https://github.com/kubernetes-client/java/issues/1362) so the update to 11.0.0 fixed that but I only experience the KubectlException. Other kubectl calls using the client work with no issues.

**Comment by brendandburns** [comment]
Since @yue9944882 pointed out above that `refreshDiscovery()` is being called, I'm surprised that you see this. Can you make sure that somehow `skipDiscovery` isn't being set to true?

Calling `ModelMapper.initModelMap()` before you do the drain should cause the right things to happen, but it's a little weird that it is necessary.

**Comment by henrymollman** [comment]
skipDiscovery is definitely not set to true, but calling `ModelMapper.initModelMap()` did solve the problem.

**Comment by brendandburns** [comment]
Ok, this is very odd, but I suspect has something to do with the way that the classes are being loaded and that static initializer not being called (or possibly throwing an exception). We should probably add some more logging code in there to help determine what is happening.

Since it is working for you with the workaround, I will close this issue, but please feel free to use `/reopen` if you find any more problems or figure out why this was occurring.
