### ISSUE TITLE
setOverridePatchFormat is removed in 9.0.2 client-java jar ClientBuilder class

### ISSUE THREAD

**Issue by srinivasev** [kubernetes-client/java#1618]
** Client Version **
`9.0.2`

I earlier used 8.0.2 client-java jar version. During creation of Client, I used the below invocation using patch format.

`public static ApiClient defaultClient() throws IOException{
        ApiClient apiClient =  ClientBuilder.standard().setOverridePatchFormat(V1Patch.PATCH_FORMAT_APPLY_YAML).build();
        return apiClient;
    }
`

After upgrading to 9.0.2 client-java jar version, setOverridePatchFormat method is missing.

My use-case:
I am using the client for patching yml content in the configmap and I see there is no deprecation comment/ info on the same. Is there any alternative option provided for using V1Patch options during creation of client.

**Expected behavior**
I think this override should be supported still.

Hi @brendanburns, any comment on this.

**Comment by yue9944882** [comment]
the `ClientBuilder#setOverridePatchFormat` method will force the ApiClient stick to my single kind of patch format, so we had [PatchUtils](https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/PatchUtils.java) or [GenericKubernetesApi#patch](https://github.com/kubernetes-client/java/blob/bfcaea2cc601ff6092f701f6bae3b64ecd32ac5b/util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java#L224) as alternatives (8.0.0+) and the `setOverridePatchFormat` is removed after another new release (9.0.0+). the example snippet is shown below:

 https://github.com/kubernetes-client/java/blob/bfcaea2cc601ff6092f701f6bae3b64ecd32ac5b/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/PatchExample.java#L67

**Comment by theAkito** [comment]
Will this ever be properly fixed? The workaround mentioned previously is not optimal.
Is there an official reason this feature got removed, in the first place?

**Comment by brendandburns** [comment]
There are no plans to fix this. You should be able to use `PatchUtils` for all interactions. Can you describe your use-case and why this doesn't work for you in more detail?

**Comment by theAkito** [comment]
@brendandburns

I didn't have a chance to test it, yet. However, I implemented basically the aforementioned example from this repository. The most obvious change is how cumbersome and less appealing the usage of this new way of using that feature is, compared to the previously available way.
Additionally, I'm not sure if casting to `PatchUtils.PatchCallFunc` is enough to make the `Call` that is returned from `patchNamespacedDeploymentCall` work, as it should. It seems like it is, but in the end everything and every call to this proc has to be tested, if it still works, after upgrading this library.

It'd be nice to know, why this feature has been made more complicated, instead of easier.

**Comment by brendandburns** [comment]
@theAkito the motivation is that the previous setting was per-client, which isn't as flexible as setting it per patch. Long term we believe the `PatchUtils` approach is the right one, and since it was a breaking change it occurred across a major version.

Whenever you upgrade major versions of this library you should expect that it is possible that there will be breaking API changes.
