### ISSUE TITLE
Watch response of ERROR causes ApiException

### ISSUE THREAD

**Issue by bhabermaas** [kubernetes-client/java#164]
When performing a watch on a list if the server returns ERROR (kind: status) there is a deserialization error because the status object differs from the Watch.Response<T>. This is particularly prevalent using custom resources.  The Watch response handler blindly uses watchType when deserializing which causes the json deserializer to throw an exception when the response object does not match the watch type.

**Comment by rjeberhard** [comment]
We think was is happening here is that the k8s api server is returning a status in the stream of objects returned by the watch as per here: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#response-status-kind

However, io.kubernetes.client.util.Watch.Response.next() simply deserializes using the target type rather than checking the kind of object and supporting a potential status.
