### ISSUE TITLE
io.kubernetes.client.openapi.ApiException: Forbidden

### ISSUE THREAD

**Issue by jchen45** [kubernetes-client/java#1693]
I always got error below, even I provided correct URL, namespace and valid OAth token:
io.kubernetes.client.openapi.ApiException: Forbidden
at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:971)
at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:883)
when I did the followings:
appsApi.listNamespacedDeployment("dev-devenablement", null, null, null, null, null, null,null,null,null);
or
rbacAuthV1Api.listNamespacedRoleBinding("dev-devenablement", null, null, null, null, null, null, null, null, null);
But it works if I call:
V1PodList list = api.listNamespacedPod("devenablement-dev", null, null, null, null, null, null, null, null, null);
What is the problem? Any idea or thoughts?
Thanks.

**Comment by brendandburns** [comment]
Your namespace is different between the calls that fail and the call succeeds.

But in general, it looks like RBAC doesn't give you permissions for those calls. You can use [`kubectl can-i ...`](https://kubernetes.io/docs/reference/access-authn-authz/authorization/#checking-api-access) to debug your access.

The fact that it works for some calls means that it is very unlikely that it is caused by this client library, but rather more likely due to RBAC on your server.

**Comment by jchen45** [comment]
Good catch! The namespace provided to the failed calls is wrong. Now it worked after right namespace provided.
Thanks!
