### ISSUE TITLE
improve watch example

### ISSUE THREAD

**Issue by ceeaspb** [kubernetes-client/java#178]
Useful to get started but the call times out after a short time. Generally I would expect it to work like with ```kubectl``` so providing the code to set no timeout may help quick start.

```
// avoid watch request timing out.
client = Config.defaultClient();
client.getHttpClient().setReadTimeout(0, TimeUnit.MILLISECONDS);
Configuration.setDefaultApiClient(client);
```

```
CoreV1Api api = new CoreV1Api();
// --- Pod watch
final Watch<V1Pod> watch = Watch.createWatch(
        client,
        api.listPodForAllNamespacesCall(null, null, null, null, 5, null, null, null,Boolean.TRUE, null, null),
        new TypeToken<Watch.Response<V1Pod>>(){}.getType());

Runnable watchTask = new Runnable() {
	@Override
	public void run() {
        watch.forEach(response -> {
        	if(response.object.getMetadata().getNamespace().equals("default")) {
        	System.out.printf("%s pod : %s%n", response.type, response.object.getMetadata().getName());
        	}
        });
	}
};
new Thread(watchTask).start();
```

**Comment by matthewrj** [comment]
I just ran into this. Thank you for posting this here, it needs to be in the example. @ceeaspb have you made a PR for this?

**Comment by rjeberhard** [comment]
When this is closed what will be the expected behavior of the sample code above?  We also need long-running watches.  Presently, we're creating watches with an explicit timeout and then wrapping this with code to reinitialize the watch.

I'd like to see this project have that utility (my team would be willing to contribute the PR).  Or, I'd be even happier if this code already does what we need.

**Comment by tingweiwu** [comment]
I use this example as follow:

```java
@Component
public class K8sWatch
{
    private Watch<V1Pod> watch;
    private ApiClient client;
    private CoreV1Api coreV1Api;
    private ExecutorService executorService = Executors.newSingleThreadExecutor();

    public K8sWatch()
    {
        try
        {
            client = Config.defaultClient();
            client.getHttpClient().setReadTimeout(0, TimeUnit.MILLISECONDS);
            Configuration.setDefaultApiClient(client);
            coreV1Api = new CoreV1Api();
            watch = Watch.createWatch(
                client,
                coreV1Api.listPodForAllNamespacesCall(null, null, null, null, null, null,null,null,Boolean.TRUE,null, null),
                new TypeToken<Watch.Response<V1Pod>>() {}.getType());
            executorService.execute(new WatchHandler());
        }
        catch (ApiException e)
        {
            e.printStackTrace();
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }
    }


    public class WatchHandler implements Runnable
    {
        @Override
        public void run()
        {
            while (true)
            {
                System.out.println(new Date()+"WatchHandler Runnable");
                try
                {
                    watch.forEach(response -> {
                        System.out.println(
                            "watchEvenet=" + response.type + " ,name=" + response.object.getMetadata().getName());
                    });
                }
                catch (Throwable e)
                {
                    System.out.println(e);
                    try
                    {
                        Thread.sleep(1000*5);
                    }
                    catch (InterruptedException e1)
                    {
                        e1.printStackTrace();
                    }
                }
            }
        }
    }
```

when I run this, after returns all added event, it throw IO Exception during hasNext method. what means this

```shell
Thu May 03 10:03:50 CST 2018WatchHandler Runnable
watchEvenet=ADDED ,name=kube-scheduler-host-10-31-3-107
watchEvenet=ADDED ,name=rc-centos-zpxx2
watchEvenet=ADDED ,name=calico-node-g7zmd
watchEvenet=ADDED ,name=calico-node-fqlnk
....................
java.lang.RuntimeException: IO Exception during hasNext method.
Thu May 03 10:05:33 CST 2018WatchHandler Runnable
java.lang.RuntimeException: IO Exception during hasNext method.
Thu May 03 10:05:46 CST 2018WatchHandler Runnable
```

additionally, after catch IO Exception  I use kubectl to delete pod, I did not receive deleted event from watch. why?
how can I permanently watch pods status ?

**Comment by aman1989v** [comment]
Hi All, I am facing a similar issue, created a watch service for nodes and pods but it is not collecting correct data at run time. To test it I ran a script to delete 5 pods and then create 5 new pods at an interval of 5 minutes. I ran watch service to see if it captures the correct result. Watch service tends to capture correct result for about 2 hours and then I saw discrepancy, I guess it is because of Watch service restarts it shows incorrect results. The actual number of active pods and number of pods that watch service is showing were different!. 
Please find the below code. 

Configuration.setDefaultApiClient(client);
		client.getHttpClient().setReadTimeout(180, TimeUnit.SECONDS);
		api = new CoreV1Api(client);
ExecutorService executorService = Executors.newFixedThreadPool(1);

executorService.execute(() -> {
			try {
				watchPods();
			} catch (Exception e) {
				e.printStackTrace();
				try {
					Thread.sleep(15000);
				} catch (InterruptedException e1) {
					e1.printStackTrace();
				}
			}
		});

private void watchPods() throws ApiException {
		while (true) {
			Watch<V1Pod> watch = Watch.createWatch(client, api.listPodForAllNamespacesCall(null, null, null, null, null,
					null, null, null, Boolean.TRUE, null, null), new TypeToken<Watch.Response<V1Pod>>() {
					}.getType());

			for (Watch.Response<V1Pod> item : watch) {
    V1PodStatus podStatus = item.object.getStatus();
    String name = item.object.getMetadata().getName();
    String status = podStatus.getPhase();
    String kind = item.object.getKind();
    String details = podStatus.toString();

    System.out.printf("NAME: %s | KIND: %s | STATUS: %s | DETAILS: %n%s%n====================%n", name, kind, status, details);
	}

			}
			System.out.println("Restarting watchPods()");
		}

	}

Let me know what changes are required to get the updated pods result.
