### ISSUE TITLE
Kubernetes secret .dockerconfigjson doesn't accept base64 encoded value

### ISSUE THREAD

**Issue by tylerXMD** [kubernetes-client/java#1797]
Similar issue that another project had: https://github.com/hashicorp/terraform-provider-kubernetes/issues/145

The Kubernetes documentation expects there to be base64 encoded data in the yml file for secrets with type "kubernetes.io/dockerconfigjson" ([link](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)).  However, if you put the base64 encoded data into the V1Secret object and call core api createNamespacedSecret(), you get the error "invalid character 'e' looking for beginning of value".

Based on the documentation, I would expect to have to encode the string before putting it in the secret's data[".dockerconfigjson" ], but it only appears to work if the string is NOT encoded.

**Comment by brendandburns** [comment]
This is working as intended.

The YAML file needs the value to be base64 encoded because otherwise it might interfere with the YAML parsing. This restriction isn't true in Java code, so in the Java code we just accept the secret because it is easier for the end user to handle that way. We take care of the base64 encode/decode ourselves in the Java code.

This question comes up from time to time, so it may be worth adding to our FAQ.
