### ISSUE TITLE
ApiExceptions in stacktraces don't contain the HTTP status

### ISSUE THREAD

**Issue by bergerst** [kubernetes-client/java#1828]
**Describe the bug**
When an ApiException is caused by a Kubernetes API call and the HTTP status message is empty, the stacktrace will only show `ApiException: `.

The status code is not printed and therefore make it more difficult to find out why the API call failed.

The issue can probably be fixed easily by changing every instance of `throw new ApiException(` to include more than the status message: https://github.com/kubernetes-client/java/blob/e253e6fa9cc0cba2033915d72157b93311fae034/kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java#L946

**Client Version**
`13.0.0`

**Kubernetes Version**
`1.11.0`

**Java Version**
Java 11

**To Reproduce**
1. Call any API with an invalid token, for example `AppsV1Api.listNamespacedDeployment()`
2. Inspect the stacktrace

**Expected behavior**
The stacktrace should contain the HTTP status.

**Comment by brendandburns** [comment]
fwiw, the status code is available in the exception:

https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/ApiException.java#L79

I think the write way to handle exceptions is to use the exception object not blindly call printStackTrace(), but if you did want to fix it, you need to fix it in the code generator since all of this code is generated.

Closing since this isn't actionable here.

**Comment by bergerst** [comment]
Did you overlook my suggestion?

> The issue can probably be fixed easily by changing every instance of `throw new ApiException(` to include more than the status message

That part is not auto-generated and it adds the benefit of not having to implement custom error handling code for ApiExceptions.

The stacktrace is printed in most Java applications automatically, for example like this:
```java
catch (ApiException e) {
  logger.error("The Kubernetes API call failed", e);
}
```
