### ISSUE TITLE
How to use CoreV1Api for tests

### ISSUE THREAD

**Issue by wind57** [kubernetes-client/java#1842]
I have a bit of a question on how to use `CoreV1Api` (for example) when performing tests. As a counter part, [here](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/ConfigMapWithPrefixTests.java) is how we currently do write tests using `fabric8`. The idea they employ is rather simple. They provide an Extension that will "inject" (it relies on reflection, obviously, under the hood) the `KubernetesClient` field, if such exists.

Later, you can use this client to issue any type of operations it supports (that tests simulates the creation of a config map); but, of course they are mocked. And when your application queries that config map, it will be served from the mock.

This allows us in spring to write tests that are very verbose and excellent (imho) to read and maintain (until that reflection part internally on their side starts failing, but its a long time there). 

So my question is : how do I test an application using the same mind-set, if possible at all. If not, and you took a different approach, I would very much appreciate some hints. 

I'm sorry upfront if this was already asked, or I missed it in the documentation. Thank you. 

---

As an addendum, we currently use WireMock when testing k8s-client in spring, and there are no problems with that at all. I was just wondering what the maintainers of this project recommend.

**Comment by brendandburns** [comment]
We use WireMock for all of the testing that we do. You can see an example here:

https://github.com/kubernetes-client/java/blob/master/extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlApplyTest.java#L56

So you need to lay in the right WireMocks for the paths that the content you want to return. It's time-consuming but more comprehensive.

You can either take that approach, or trust that we've done a good job testing things like the client API and use a tool like Mockito to create a mock `CoreV1` object and inject that into your code.

I prefer the WireMock approach, because in practice I have found everywhere that you introduce a mock, you introduce a gap between reality and your tests where bugs/inconsistency in the tests can lead to problems in production, but obviously it can make it much harder to write the tests, which can mean fewer tests, which can mean more bugs, so it's a trade-off.

**Comment by wind57** [comment]
thank you very much for your answer. The problem is not "trust" here, at all. It's just a shift of paradigm in testing. I am in no shape or form affiliated with Spring, but as a committer there - this is what I feel. A mock client moves the burden away from defining or even having the understanding of the kube-api-server. imho: it makes testing easier, though your arguments do make perfect sense too.  There is no problem defining WireMocks stubs and this is what I do, yes. 

Your reply and recommendations are highly appreciated. I will close this question, as I got my answer.
