### ISSUE TITLE
Can I get the current namespace from CoreV1Api/ApiClient

### ISSUE THREAD

**Issue by wind57** [kubernetes-client/java#1857]
I thought this should be out of the box, but after I kind banged my head against the wall for a while, I need to ask:

so is there a way for me to get the "client's namespace" where it is currently running? And if you have the question "why would you need that?" Consider the simplest case we have in spring:

Our users can tell us which secret they want to read and which namespace they want to read it from. They can omit both of these. When they omit `name`, we can easily default it to `spring.application.name` if it is present, or simply the plain String `application`. 

For `namespace`, it is rather weird to "default" it to something. Ideally, we would need to know what namespace is the client running in, and default to that...

Thank you.

**Comment by yue9944882** [comment]
@wind57 as far as i know there's basically two native ways to acquire the hosting namespace from an application:

- if the application is running as a container inside the kubernetes cluster, it is supposed to mount a service-account secret in which there's a property named `namespace` mostly mounted on `/var/run/secrets/kubernetes.io/serviceaccount/namespace`. but note that the container can sometimes opt-out from mounting the service-account tho.

- another way is to mount the namespace as an env-var or files via [downward-api](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/). this will require a few explicit modification on the pod spec unless we have an admission webhook to intercept and do the namespace injection.

**Comment by brendandburns** [comment]
Yeah, there's no way to do this via the Kubernetes API. You could potentially maintain an index of (IP address -> Pod def) and then use the client's IP address to find the Pod definition and the namespace for the Pod, but you'd have to do that yourself (and depending on the details of your network config the client IP may or may not be preserved anyway)

The only other thing you could do is define an instance of your Service in every namespace and point each one at a different port on your application. Then you would know which namespace was calling you based on the port that it came in on, but that would be complicated to maintain, especially in an environment where namespaces are dynamically coming and going.

I'm going to close this issue since there is really nothing we can do here.

**Comment by wind57** [comment]
thank you both for your answers, very helpful!

**Comment by wind57** [comment]
@yue9944882 

> but note that the container can sometimes opt-out from mounting the service-account tho

really? I thought you can disable token mounting _only_ via `automountServiceAccountToken`.

Yeah, downward-api is a possibility indeed, but currently we do not support that in spring. From what I've searched the issues - there was not a single issue or request for this. It will stay un-implemented on our side until there is such a demand. Thank you for the excellent reminder, though!

@brendanburns thank you for the explanation, makes sense. As usual :)
