### ISSUE TITLE
`V1JSONSchemaPropsBuilder` doesn't support field `xKubernetesPreserveUnknownFields`

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [kubernetes-client/java#1978]
**Describe the bug**
The `V1JSONSchemaPropsBuilder` doesn't support the field `xKubernetesPreserveUnknownFields` so you can't set it in a fluent style.

**Client Version**
`11.0.2` but from looking at the code the issue also seems to be in the latest `14`

**To Reproduce**
As part of a `V1CustomResourceDefinition` you need a snippet like:
```
V1CustomResourceValidation crdValidation = new V1CustomResourceValidationBuilder()
    .withOpenAPIV3Schema(new V1JSONSchemaPropsBuilder()
        .withType("object")
        .build())
    .build()

crdValidation.getOpenAPIV3Schema().setxKubernetesPreserveUnknownFields(true);
```
to successfully set the `xKubernetesPreserveUnknownFields` field.

You can't set it in the `V1JSONSchemaPropsBuilder` because there's no method for it and if you set it after the `build()` invocation it doesn't get copied over by `withOpenAPIV3Schema` because this method creates a new `V1JSONSchemaPropsBuilder` object which again doesn't know about the field.

**Expected behavior**
```
new V1CustomResourceValidationBuilder()
    .withOpenAPIV3Schema(new V1JSONSchemaPropsBuilder()
        .withType("object")
        .withXKubernetesPreserveUnknownFields(true))
        .build()
    .build()
```
should work.

**Comment by brendandburns** [comment]
I think that this is a duplicate of #1930

**Comment by dennis-benzinger-hybris** [comment]
/reopen

I don't see how this is a duplicate of #1930. My previous ticket was about loading this property from YAML files. Now it's about setting it in the fluent Java API.

In gist https://gist.github.com/dennis-benzinger-hybris/c432d62568d8d029e056dac5ff9c308a I've reproduced the issue with version 14 of the client.

**Comment by yue9944882** [comment]
@dennis-benzinger-hybris thx for reporting this. the `x-kubernetes-...` properties are ignored b/c their setter method name conflicted w/ the filtering logic in the builder generator:

https://github.com/sundrio/sundrio/blob/533e4b9b6ecc6ed2c9580c20162d296378e7a6f0/model/utils/src/main/java/io/sundr/model/utils/Setter.java#L88-L91
e.g. the original generated setter/getter for `V1JSONSchemaProps`'s `xKubernetesEmbeddedResource` is actually `setxKubernetesEmbeddedResource` of which the `x` is expected to be capitalized otherwise ignore.

**Comment by yue9944882** [comment]
/kind bug

i will find a workaround for fixing this
