### ISSUE TITLE
How to Get POD Details(PODId, Status, HostIP and Port) while using MiniKube.

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [kubernetes-client/java#1982]
**Describe the bug**
We have deployed our Java App(With Application server), having 3 replicas within a single cluster and namespace.
So whenever each server(Pod) is starting, trying to get following details related to respective POD,
      1. PodID, HostIP and Port associated with Pod which is starting,
      2. Once I get a particular PodID, any API which would take PodID as input and return the status of the POD.

I did try PodStatus.getDefaultInstance().getPodIP() and PodStatus.getDefaultInstance().getHostIP() but those gave empty output.

**Client Version**
10.0.0

**Kubernetes Version**
GitVersion:"v1.21.5"
**Java Version**
Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**

**Server (please complete the following information):**

**Additional context**
Yaml looks like,
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: XXXXXXXXXXXXXX:tag2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: "http"
        - containerPort: 5005
          name: "debug"
---
apiVersion: v1
kind: Service
metadata:
  name: greeting
spec:
  selector:
    app: greeting
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
`

**Comment by brendandburns** [comment]
What is the code that you are running? It's hard to know what is going wrong without seeing the code.

**Comment by brendandburns** [comment]
If the code is `PodStatus.getDefaultInstance().getPodIP() and PodStatus.getDefaultInstance().getHostIP()` then that is not going to work. You need to talk to the API server to get access to the pod details.

Otherwise, you can use the downward API: https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#the-downward-api to expose some information as environment variables.

**Comment by PSHREYASHOLLA** [comment]
What is the code that you are running? It's hard to know what is going wrong without seeing the code.

>>>>>As mentioned in description, we have a Java App deployed on Application server like JBoss/Apache tomcat. On POD Startup my application starts on an application server and  inside my java code I want to get following details,
1. PodID, HostIP and Port associated with Pod which is starting,
2. Once I get a particular PodID, any API which would take PodID as input and return the status of the POD.

From the example associated with this Project I got the code like,
ApiClient client;
			
            CoreV1Api api = new CoreV1Api();
            V1PodList list;
            client = Config.defaultClient();
	    Configuration.setDefaultApiClient(client);
            list=api.listNamespacedPod(null, null, null, null, null, null, null, null, null, null);
This would give me the entire POD list, but what I am looking for as mentioned earlier,

1. PodID, HostIP and Port associated with Pod which is starting,
2. Once I get a particular PodID, any API which would take PodID as input and return the status of the POD.

**Comment by brendandburns** [comment]
You will need to use the downward API as described above to get access to the details of your pod. The hostname of your pod is typically also it's name. 

Once you have the name and namespace your Pod you can use `client.readNamespacedPod(...)` to get more pod details.

Closing this issue because it is more of a question of how Kubernetes works rather than an issue with this client.
