### ISSUE TITLE
How to handle ModelMapper.refresh in case of multiple K8s Clusters 

### ISSUE THREAD

**Issue by saparaj** [kubernetes-client/java#1989]
I am trying to use kubernetes java client with multiple K8s Clusters - I am setting up api client using kubeconfig of each cluster and then passing this api client to respective kubectl calls like apply or get.

I can see we have implicit refreshDiscovery call in executeServerSideApply() method, as ModelMapper classes are all static, how should multi-tenant scenario be handled? These discovery classes will be used across threads for concurrent apply calls and will cause transient errors. Thank you.

Kubernetes Java Version
13.0.1

Kubernetes Version
v1.20.11

**Comment by brendandburns** [comment]
Those `kubectl` style classes were mostly written for people to learn how Kubectl worked. For now if you want to handle multiple clusters from the same code you will need to use the more raw Kubernetes APIs instead of the kubectl implementations.

We would take PRs to make the discovery cache be per-server rather than global if you are willing to send them.

**Comment by yue9944882** [comment]
the binary kubectl command manages discovery caches by separating them into folders w/ the name of the master endpoint. we will need a per-server cache for multi-cluster cases.
