### ISSUE TITLE
Usage: Interaction between PODS of the same application deployed in different Nodes

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [kubernetes-client/java#1997]
Hi,

We are getting list of PODS using the following API,
ApiClient client;
V1PodList list;
client = Config.defaultClient();
Configuration.setDefaultApiClient(client);
CoreV1Api api = new CoreV1Api();
				list=api.listNamespacedPod("default", null, null, null, null, null, null, null, null, null);
				 for (V1Pod item : list.getItems()) {
		                System.out.println("HostIP: "+item.getStatus().getHostIP());
		                System.out.println("PODIP: "+item.getStatus().getPodIP());
		            }

So here once we get the PODIP, we are trying to communicate within PODS using this internal PODIPs retrieved.
Scenario 1: All PODS are deployed in same Node. In this case inter pod communication is working fine.

Scenario 2: PODS are deployed in different nodes,
                   So in this case will we be able to access a POD in different node using PODIP retrieved from above API?

**Comment by brendandburns** [comment]
This isn't really a client question. It is a Kubernetes question.

The answer is: Yes, assuming your cluster is properly configured pods should be able to talk to each other using pod ip addresses regardless of what nodes they are on.

There is lots of good documentation about Kubernetes in https://kubernetes.io.

In the future, I would recommend using that documentation or the general Kubernetes community on slack (https://slack.kubernetes.io) for answering these kinds of questions rather than the Java client issue queue.

The java client only has a few maintainers with limited time and so you are much more likely to get timely answers from other sources.

Thanks.
