### ISSUE TITLE
How to get pod info like use "kubectl describe pod xxxxx" and get Events info

### ISSUE THREAD

**Issue by momomobinx** [kubernetes-client/java#2142]
`
Events:
  Type     Reason   Age                     From     Message
  ----     ------   ----                    ----     -------
  Normal   BackOff  6m19s (x586 over 141m)  kubelet  Back-off pulling image "busybox:v1.0"
  Warning  Failed   87s (x32 over 141m)     kubelet  Failed to pull image "busybox:v1.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/library/busybox:v1.0": failed to resolve reference "docker.io/library/busybox:v1.0": docker.io/library/busybox:v1.0: not found
`

**Client Version**
`14.0.0`

**Kubernetes Version**
 `1.21.3`

**Java Version**
 Java 8

**Server (please complete the following information):**
 - OS: Centos

**Comment by momomobinx** [comment]
Use this ? Has other way?
`
CoreV1EventList events = coreV1Api.listNamespacedEvent("namespace",null,null,null,null,null,null,null,null,null,null);

        System.out.println("  Type     Reason   Age                   From     Message");
        System.out.println("  ####     ####   ####                  ####     #######");
        for(CoreV1Event event : events.getItems()) {

            if(event.getInvolvedObject().getName().equals("pod-name"))
            {
                System.out.println("  "+event.getType()+"     "+ event.getReason()+"   AGE                   "+event.getSource().getComponent()+"     "+event.getMessage());

            }
        }

`

**Comment by brendandburns** [comment]
`kubectl describe ...` is a pretty complicated piece of client side code. It integrates a bunch of different API calls. If you are interested in the events, then yes, that code is the best way to get the events.

I'm closing this issue since it is currently out of scope for the library. If you want to implement it, we have some kubectl equivalent commands here:

https://github.com/kubernetes-client/java/tree/master/extended/src/main/java/io/kubernetes/client/extended/kubectl

We'd gladly take a PR to add more.
