### ISSUE TITLE
Helpful enum values in model classes reverted in 15.0.1

### ISSUE THREAD

**Issue by rjeberhard** [kubernetes-client/java#2218]
The 15.0.0 release updated the generated model classes with helpful enum classes, e.g. for imagePullPolicy legal values in V1Container. Now, the 15.0.1 release reverts these improvements. 

I've already gone through the pain :) of updating our usage to the 15.0.0 pattern. Why were these changes reverted? Will the enum classes come back in a later version? Thanks!

**Comment by yue9944882** [comment]
@rjeberhard it is reverted due to https://github.com/kubernetes-client/java/issues/2192. we're seeing some complaints about broken enum types. the new enum type is controlled by a feature-gate named `OpenAPIEnumType` which is still under unstable alpha phase. we will surely land onto that after that feature graduate into beta, hopefully next release or next next release.
