### ISSUE TITLE
Improved documentation for watching custom resources

### ISSUE THREAD

**Issue by jmcrawford45** [kubernetes-client/java#2240]
I've been trying for a few hours to figure out what the expected workflow is for watching custom objects. Basically, I want to setup something in scala similar to https://www.baeldung.com/java-kubernetes-watch for custom objects. I followed https://github.com/kubernetes-client/java/wiki/5.-Generate-Java-CRD-Model for generating custom resource classes. I was able to get a resource version by applying a hack I saw in another github issue
`val tsdList = {
      clients.head.listClusterCustomObjectCall(
        ...
      )
    }
    val response = tsdList.execute()
    if (response.isSuccessful) {
      val body = response.body().string()
      gson
        .fromJson(body, classOf[CustomResourceList]).getMetadata.getResourceVersion
    } else null`

But, when I try to watch the resource, I get a response with everything (status, type, object) set to null and no clear indicator of what's happening.

`    val call = clients.head.listClusterCustomObjectCall(
      ...
      resourceVersion,
      if (resourceVersion != null) "NotOlderThan" else null,
      ...
    )
    val watch: Watch[Object] = Watch.createWatch(
      clients.head.getApiClient,
      call,
      new TypeToken[Response[Object]]() {}.getType)`

Is there some other way that custom resources are expected to be handled?

**Comment by brendandburns** [comment]
I don't really know Scala, but I assume that `Watch[Object]` means `Watch` which returns `Object`. I think that you want to parameterize your `Watch` with the concrete type that you generated for your CRD.

The watch example is here:
https://github.com/kubernetes-client/java/blob/master/examples/examples-release-15/src/main/java/io/kubernetes/client/examples/WatchExample.java

It is for a built-in type, but I _think_ it should work if you use your generated types.

If it doesn't let us know.

Note that we will need standard Java, not Scala code, since the authors of this project are not necessarily Scala experts.

**Comment by jmcrawford45** [comment]
I haven't been able to get the watch to work even when using the type of the implementor of KubernetesListObject. I'll try to repro in java or translate what I have currently and share tomorrow. Thanks for looking into this.
