### ISSUE TITLE
How to handle Spring + Java 8?

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#2452]
Spring has moved to require Java 17 with Spring 6 (https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6)

We probably want to continue to support Java 8 + Spring 5, and this library will keep moving forward with new Kubernetes releases.

So we need to figure out how to move forward here.

I think the best thing to do is probably to extract the code from the `extended` package into a separate `spring-6` package which can take a dependency on the new spring code.

Note that this is less than ideal because we will have a bunch of code duplication and probably start having feature skew between the two packages.

cc @yue9944882 @joshlong

Does anyone know how other libraries are approaching this?

**Comment by joshlong** [comment]
Hi 

It is possible to share the base Spring Boot 2 autoconfiguration (assuming you add a text file called `AutoConfiguration.imports`) for both Spring Boot 2 and Spring Boot 3. The only part unique to Spring Boot 3 is the new AOT engine. so, perhaps you could create a `starter-aot` (or something) which in turn imports the core `starter`. that way people using Spring Boot 3's AOT engine could use that, and everybody else could just use the regular `starter`, which works in both boot 2 and 3, and on java 8 or later.

I prototyped this to see if it'd work out in practice by building a regular `starter` (for both boot 2 and 3), a `starter-aot` (for just boot 3), an `app-2` to use the regular `starter`, and an `app-3` to use the `starter-aot`. 

https://github.com/joshlong/hybrid-2-and-3-spring-boot-starters 

it seems to work. maybe there's a better way, but at least this works. 

NB: 

* I had to add a new (text-)file from boot 3 to the otherwise boot 2 `starter` so that it'd function in both boot 2 and 3 
* I setup `.sdkmanrc` files so that the two boot 2 projects - the `starter` and `app-2` assume a java 8 compiler, while the boot 3 projects - `starter-aot` and `app-3` -  assume java 17

**Comment by dsyer** [comment]
+1 - it should be trivial to support Spring Boot 2 and 3 without a separate jar artifact. At least we should start that way. We could maybe drop Spring Boot 2 when the Kubernetes client reaches a new major, but it's probably not going to be mandatory.

**Comment by brendandburns** [comment]
The problem has to do with compiling the spring code in this library. (and it's not just about spring boot, it's about spring generally)

We're going to target Spring 5.x for now because we need to maintain Java 8 compatability. That means that we can't take a dependency on Spring 6 from this library. Hence the need to split the code so that one library can depend on spring 5 and the other can depend on spring 6.

**Comment by joshlong** [comment]
right. that's basically what my prototype demonstrates. i wouldn't bifurcate them in terms of spring framework 5 and 6, but instead in terms of the auto configuration (available in all versions of Spring Boot) and the ahead-of-time (AOT) compilation for graalvm (unique to SF 6 / spring boot 3) support. 

so you'd leave the auto configuration as-is, but add one text file, `META-INF/spring/...AutoConfiguration.imports`. that jar links to SB 2 and compiles with java 8. it'll work in SF 6 and SB 3, too.

then you introduce a new jar, which in my prototype I've called `starter-aot`, which pulls in `starter` but then also contributes AOT 'hints' to make the `starter` work when compiled in a graalvm app. 

SB 3 users could pull in `starter` OR `starter-aot` (i'd encourage them to use `starter-aot`, since graalvm's dope and there's no high quite like the high of a well-written kubernetes controller written on the JVM and spring boot that takes 50mb of RAM!) 

SB 2 users pull in `starter` (eg, nothing changes for them at all) 

wdyt?

**Comment by brendandburns** [comment]
@joshlong thanks for the details, it feels like this would be a good approach. Basically if you can craft a PR that passes our integration testing we're good with it :)

**Comment by joshlong** [comment]
hi - i have just sent this PR. it changes almost nothing from the existing `client-java-spring-integration` module, adding only one text file. It also adds a new module to specifically support Spring Boot 3 AOT.

https://github.com/kubernetes-client/java/pull/2457

**Comment by dsyer** [comment]
/remove-lifecycle stale

(But #2457 is merged, so why is this one still open?)

**Comment by dsyer** [comment]
/remove-lifecycle stale

(But https://github.com/kubernetes-client/java/pull/2457 is merged, so why is this one still open?) Someone should just close this as “fixed”.

**Comment by dsyer** [comment]
Sigh. Dumb robot. If anyone is reading this please be assured that it is fixed.
