### ISSUE TITLE
Load partial information

### ISSUE THREAD

**Issue by jnt0r** [kubernetes-client/java#2502]
Is it possible to only load specific fields from resources like name or all metadata fields?

I have a project where I need the name of all deployments from all namespaces. Currently, I read all deployments with every field contained and then map every deployment to the name, as I only need the name. In case of bandwidth and memory usage, it would be cool to only load the names or even the metadata of the deployments without every other field I don't need.

Is this possible, or does the kubernetes API not support this?

**Comment by brendandburns** [comment]
The Kubernetes API doesn't support this. Each JSON object is returned in full.

If you wanted to do this, the best thing to do would probably be to run a GraphQL server inside your cluster, and then use GraphQL to talk to the Kubernetes API. Of course this will be tricky to get RBAC etc correct.

Closing since this isn't currently feasible, apologies.
