### ISSUE TITLE
List of Node Pools/Groups using kubernetes-client library

### ISSUE THREAD

**Issue by pawank0411** [kubernetes-client/java#2535]
Hi @brendandburns

Can we get the list of **Node groups/pools** with some details like max node count, min node count etc

I researched a bit, but I didn't found something `kubectl get node-pools`

**Comment by brendandburns** [comment]
Node groups/pools aren't really a Kubernetes concept. They are something that is sometimes layered on top by specific Kubernetes providers.

There's no standard resource for `node-pool` if you have a cluster with a special CRD installed for node pools, you can use the generic client to access that CRD.

Closing this issue because there's nothing to do in this client.
