### ISSUE TITLE
ControllerManager/DefaultController error handling

### ISSUE THREAD

**Issue by olegsavin** [kubernetes-client/java#2689]
**Describe the bug**
[ControllerManager](https://github.com/kubernetes-client/java/blob/57a9c55fa48d25cfb2bc461c6fd97bce87ca4433/extended/src/main/java/io/kubernetes/client/extended/controller/ControllerManager.java#L68)/[DefaultController ](https://github.com/kubernetes-client/java/blob/57a9c55fa48d25cfb2bc461c6fd97bce87ca4433/extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java#L142)do not throw/retry if any of controllers fails preFlightCheck.
DefaultController silently exits run() func, ControllerManager doesn't do anything about it, doesn't re-try or throw also.
There is no way for outside consumer to figure out if all controllers have been started fine or not and retry if not.

**Client Version**
18

**Kubernetes Version**
1.26

**Java Version**
Java 11

**To Reproduce**
Hard repro, API server REST call timeout caused this.

**Expected behavior**
Client/consumer of ControllerManager should be able to specify what happens in case not all controllers start successfully - best effort or hard fail ControllerManager.run(). Expose running status of controllers. Exception in preFlightCheck should be propagated to client or client is able to provide custom handler - for individual controller and combined all failures of controllers registered in ControllerManager,

**Comment by brendandburns** [comment]
We'd be happy to take PRs to improve the behavior here.

**Comment by kvmw** [comment]
We ran into the same issue, because one of our controllers was registered to list/watch a CRD type which was not there yet. The CRD was provided by another deployment and it just happened that our deployment was faster than the other one and the controller informer was trying to list the CRD type which was not there yet. 

A simple way to reproduce this issue is by making sure that `readyFuncs` always return false.  
If `readyFuncs` does not return true in 30 seconds (default timeout), pre-flight check fails and controller exits run() function without any error or failure signal. 

Exposing the status of the controllers (including ControllerManager) would be sufficient to solve the issue. The status can be used in probe endpoints to expose the issue and cause pod restart if needed.
