### ISSUE TITLE
[Featue Request] Expose Controller Readiness

### ISSUE THREAD

**Issue by abelsromero** [kubernetes-client/java#2742]
`DefaultController` class can accept [functions](https://github.com/kubernetes-client/java/blob/7f957585fe8fba9278c2a103a9f97cf6d1acbb9b/extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java#L54C37-L54C47) for pre-flight checks, those are run on startup and 100% private, including the method [isReady](https://github.com/kubernetes-client/java/blob/7f957585fe8fba9278c2a103a9f97cf6d1acbb9b/extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java#L120).

However, Controllers can end up in inconsistent states after being successfully started. When that happens is not possible to check if they are up*. 

If the `isReady` was made public (or any other alternative) it'd be possible to have internal probes that check if the Controllers are actually up working correctly with the same ready functions.

\* We can check if the `getWorkQueue().isShuttingDown()` and			 `getWorkerThreadPool().isShutdown()`, but that does not cover all scenarios, for example, egress to K8s API being blocked.

**Comment by brendandburns** [comment]
I think this is a reasonable feature to add. @yue9944882 what do you think?

**Comment by abelsromero** [comment]
Thinking about this today, maybe we should expose a dedicated method to check the status? Maybe the validations are not the same as the ones for pre-flights.

**Comment by kvmw** [comment]
We are running in to the similar issue. 
In our case `isReady` was returning false, due to some API call issues, so the [preFlightCheck](https://github.com/kubernetes-client/java/blob/7f957585fe8fba9278c2a103a9f97cf6d1acbb9b/extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java#L141C10-L141C24) failed and `run` method call ended without throwing any exception or error to signal the failure.  

#2689 is about the same issue.
