### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.6.0:jar 

### ISSUE THREAD

**Issue by AnityaSharma** [kubernetes-client/java#2809]
While installing the software using 
git clone --recursive https://github.com/kubernetes-client/java
cd java
mvn install
Getting an error 
![Screenshot 2023-10-03 000945](https://github.com/kubernetes-client/java/assets/123667291/2972f6fc-cd5e-4a76-8629-902206424f15)

**Comment by brendandburns** [comment]
As the error line suggests, you need to set the `JAVA_HOME` environment variable to point to the correct location in your file system.

I'm going to close this because this is not an issue with the client, but rather your local setup.

If you have further problems, please file additional issues or use the `/reopen` command to reopen this issue.
