### ISSUE TITLE
lack of documentation on listNamespacedService breaking change

### ISSUE THREAD

**Issue by gyorokpeter** [kubernetes-client/java#3100]
This worked in 19.0.0:
```
kube.listNamespacedService(namespace, null, null, null, null, labelSelector, null, null, null, null, null);
```
But it breaks in 20.0.0:
```
[ERROR]   required: java.lang.String
[ERROR]   found: java.lang.String,<nulltype>,<nulltype>,<nulltype>,<nulltype>,java.lang.String,<nulltype>,<nulltype>,<nulltype>,<nulltype>,<nulltype>
[ERROR]   reason: actual and formal argument lists differ in length
```
https://javadoc.io/static/io.kubernetes/client-java-api/20.0.0/io/kubernetes/client/openapi/apis/CoreV1Api.html#listNamespacedService(java.lang.String) makes no mention of this breaking change and how to migrate old code that requires any of the parameters other than the namespace.

Also the changelog file (https://github.com/kubernetes-client/java/blob/master/CHANGELOG.md) cuts off at 14.0.0 so no luck finding this breaking change there either.

**Comment by yue9944882** [comment]
to obtain the backward-compatible client module, adding a `-legacy` suffix to the version will do

**Comment by gyorokpeter** [comment]
In the meantime we found this example: https://github.com/kubernetes-client/java/blob/master/examples/examples-release-20/src/main/java/io/kubernetes/client/examples/WatchExample.java

It would still be useful to update the docs to better explain how to migrate from the old to the new style API.

**Comment by MartinEmrich** [comment]
The example with Watch linked above is a bit confusing to me, I cannot really deduce what to do with imperative actions.
For example: the old SDK `CustomObjectsAPI.createNamespacedCustomObject()` returned a (response) `Object`, so it did the actual deed.
 
The 20+ version not only dropped two arguments, but now returns a "...Request" Object, and inspecting the code looks like it does not actually do the request, but just creates a "request" object. How to execute the request now? Trying to run it also results in very obscure errors like `java.lang.ClassCastException: class io.kubernetes.client.openapi.apis.CustomObjectsApi$APIgetNamespacedCustomObjectRequest cannot be cast to class com.google.gson.internal.LinkedTreeMap (io.kubernetes.client.openapi.apis.CustomObjectsApi$APIgetNamespacedCustomObjectRequest and com.google.gson.internal.LinkedTreeMap are in unnamed module of loader org.springframework.boot.loader.launch.LaunchedClassLoader @64729b1e)
`.

Is there a valid new example available for e.g. `createNamespacedXXXX` or `getNamespacedXXX`?

Otherwise: Will the `-legacy` builds be provided indefinitely, or is there an end-of-life target date?

/remove-lifecycle rotten
