### ISSUE TITLE
Un maintained Opensource package being used in this project : com.microsoft.azure:adal4j

### ISSUE THREAD

**Issue by vijeyanidhi** [kubernetes-client/java#3169]
**Describe the bug**

This opensource software is using an unsupported package `com.microsoft.azure:adal4j` https://github.com/AzureAD/azure-activedirectory-library-for-java which has been in maintenance in 2021 and archived in 2023.

the project has been shifted to https://github.com/AzureAD/microsoft-authentication-library-for-java should be used in this particular project instead of the older un maintained project artifact.

**Client Version**
20.0.0

**Kubernetes Version**
Not required here

**Java Version**
Java 8, 11, 17

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by vijeyanidhi** [comment]
https://mvnrepository.com/artifact/com.microsoft.azure/adal4j/1.6.7

<img width="1110" alt="Screenshot 2024-03-08 at 01 28 37" src="https://github.com/kubernetes-client/java/assets/42498089/f1952af8-3faf-4c9a-81d1-1f0af3d75ff6">


last release was done in 2021 April

**Comment by brendandburns** [comment]
Given that this code is being deprecated in newer Kubernetes versions, we should consider just ripping out this code entirely.

**Comment by vijeyanidhi** [comment]
> Given that this code is being deprecated in newer Kubernetes versions, we should consider just ripping out this code entirely.

so I am assuming this is going to be released in version 21 or version 22? and not anytime in this week?

**Comment by codefromthecrypt** [comment]
I took a look and also tried the [migration guide](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Migrate-to-MSAL-Java). It isn't straight-forward and very likely to introduce bugs.

My recommendation would be to plan to remove this dependency as @brendandburns mentioned, and do nothing about it otherwise. To do something otherwise would both require very strong rationale, and also be in concert with an actual user of this project and specifically the active directory component.

My 2p, and I'm not a maintainer, so take it for what it's worth.

**Comment by codefromthecrypt** [comment]
raised this to buy some time https://github.com/kubernetes-client/java/pull/3175
