### ISSUE TITLE
java.net.SocketTimeoutException on watch

### ISSUE THREAD

**Issue by lmeunier-talend** [kubernetes-client/java#352]
Hi

I'm watching on all the event for pods.

My code is kinda the same as your watch example but for the fact I'm working on pod and I saw there was a closed issue about this.
My problem is that setting the timeout like you suggested do nothing.

This feature would have been really nice in my case, and it's working well for about 20 secondes...

I guess I would have to use a scheduler instead and query at interval.

**Comment by brendandburns** [comment]
You should expect some `SocketTimeout` on watch due to vaguaries in the internet, but 20 seconds is too short for that....  So I suspect that you need to set the socket timeout values on the OK HTTP client:

See this link:
https://github.com/kubernetes-client/java/issues/150#issuecomment-352514928

for a suggestion that seemed to have worked for another user.

If that's not working, please send the code snippet you are using and we can see what's going wrong.

Thanks!

**Comment by brendandburns** [comment]
Closing this as obsolete, please re-open if you still need help.
