### ISSUE TITLE
Any generic api in io.kubernetes.client.apis.*Api.java ?

### ISSUE THREAD

**Issue by impatrickwang** [kubernetes-client/java#358]
when doing same operation on different kinds of kubernetes resources of same version, I need to call different apis in same *Api.java. Is there any generic api can handle operations on different types of resource?

For example, when creating Deployment, the method stack is:
     createNamespacedDeployment
-> createNamespacedDeploymentWithHttpInfo 
-> createNamespacedDeploymentValidateBeforeCall 
-> createNamespacedDeploymentCall, 
at last it will create a okhttp.Call, 
while creating DaemonSet, the method stack is: 
     createNamespacedDaemonSet 
-> createNamespacedDaemonSetWithHttpInfo 
-> createNamespacedDaemonSetValidateBeforeCall 
-> createNamespacedDaemonSetCall, 
it also create a okhttp.Call.

The only difference is the resource part in the url path.

If there is a generic method that accept one more parameter that indicates the type of kubernetes resource, it can dynamically operate different kinds of kubernetes resource.

**Comment by zenglian** [comment]
IMO the current design can be **greatly simplified** by taking advantage of basic features of OOP like **inheritance** and **polymorphism**. Take these operations for example
- resource classes of `V1XXXX` (by the way should the the version number be a part of all classes?) should inherit a base class `ResourceBody` as obviously they have a lot common fields.
- custom resource should inherit it too instead of a plain Object
- `api.createXxx` (CRUD) can be unified into one `api.createResource`. It should know the resource type by checking the `kind` field of the `body` or the instance type of the `body` object
- etc, etc ......

then we could have much fewer methods and fewer arguments of the methods, and it should benefit both the implementers and users a lot. That's why OOP is popular (for many years).

**Comment by brendandburns** [comment]
All of this code is generated by the swagger-codegen library.

We use generated code so that we can easily update as the Kubernetes API changes.

If you want to make changes to the generated code, the template for the code is here:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache

I've found them to be very responsive to updates and PRs in the past, so definitely send a PR their way.

Regarding inheritance, Swagger 2.0 doesn't support inheritance, Swagger 3.0 does support it, but we need Kubernetes to update to Swagger 3.0

I'm going to close this issue, since it's not something that we want to address in the context of this repo.

Please re-open if you'd like further clarification or discussion around these issues.

Thanks!
