### ISSUE TITLE
Can't load $HOME/.Kube/config when running on Windows

### ISSUE THREAD

**Issue by yu-shiba** [kubernetes-client/java#386]
`io.kubernetes.client.util.KubeConfig#ENV_HOME` is fixed at "HOME", but $HOME is not set under Windows environment.
Therefore `io.kubernetes.client.util.ClientBuilder#findConfigInHomeDir()` fails and can not read config file.

In "client-go" it corresponds to this problem the following code
https://github.com/kubernetes/client-go/blob/master/util/homedir/homedir.go

but it does not seem to consider "client-java".

**Comment by brendandburns** [comment]
Acknowledged. Will fix.

**Comment by 1u0** [comment]
@brendanburns, fyi, this is not working on Windows due to NPE:
the `System.getenv(ENV_HOME)` returns `null`, which is not valid pathname for `File` constructor.
So the following Windows specific code, in https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/ClientBuilder.java#L120-L146
is not reached.
