### ISSUE TITLE
Determine where the right home for client extensions are...

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#45]
When I wrote Exec I placed it in the `util` directory, because I wanted everything in `kubernetes` to be generated code.

When @mbohlool added Watch he placed it in `kubernetes`

We should only place clients in one place. This issue is to figure out where that is.

@mbohlool , @lwander I think separating generated from non-generated code is the right idea as it will make management easier in the long term.  What do you think?

Thanks!

**Comment by mbohlool** [comment]
Yes. Python client has that distinction. That was a mistake on my side. I
will move watch to util package. We eventually should move all non
generated code into java-core repo to follow clients guideline.

On Jun 30, 2017 8:58 PM, "Brendan Burns" <notifications@github.com> wrote:

When I wrote Exec I placed it in the util directory, because I wanted
everything in kubernetes to be generated code.

When @mbohlool <https://github.com/mbohlool> added Watch he placed it in
kubernetes

We should only place clients in one place. This issue is to figure out
where that is.

@mbohlool <https://github.com/mbohlool> , @lwander
<https://github.com/lwander> I think separating generated from
non-generated code is the right idea as it will make management easier in
the long term. What do you think?

Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes-client/java/issues/45>, or mute the thread

**Comment by lwander** [comment]
Agreed - SGTM

**Comment by brendandburns** [comment]
Closing this since we have consensus (and I merged @mbohlool's move of the Watch API)
