### ISSUE TITLE
[Custom Classloader]Unknown apiVersionKind with empty known kinds in Yaml

### ISSUE THREAD

**Issue by gavinfish** [kubernetes-client/java#474]
Same error as #365 , even though my version is 3.0.0.

I use this SDK in Jenkins plugin which defines custom classloader.

Now this SDK uses `ClassPath cp = ClassPath.from(Yaml.class.getClassLoader());`  to load the related classpathes. And the ClassPath will use code https://github.com/google/guava/blob/f15fdd10cd1e3e81ad2c31f555dfaaf70a72cf69/guava/src/com/google/common/reflect/ClassPath.java#L444-L468 to find the classloader classpath. And it seems that if the `Yaml.class.getClassLoader()` is a not sub class of `URLClassLoader`, it will not find its related classpath. Any solution here? Thanks.

**Comment by gavinfish** [comment]
@brendandburns any suggestions here?

**Comment by brendandburns** [comment]
You could definitely update `initModelMap` to take a class loader as a parameter if that would help.

Basically what we need here is some way to walk through all of the generated Model classes and build up a mapping of known API versions and resources.

You could also break the function so that it just takes an array of `Class` objects, and then figure out the right way to find the `Class` files for the model objects in your context.

I have to admit the Classloader stuff in Java is arcane enough that I barely learned enough to get what I needed done....

**Comment by johnlabarge** [comment]
Hey there I'm dealing with the same thing.  Did you make any progress?

**Comment by runzexia** [comment]
@johnlabarge Hey there I'm dealing with the same thing in jenkins. Did you make any progress?

**Comment by runzexia** [comment]
The classloader is very complicated, I wonder if I can avoid the classloader and then initialize this part through code generation.

**Comment by gavinfish** [comment]
Thanks for @runzexia . We now generate the target classes and manually load them. Details at jenkinsci/kubernetes-cd-plugin#87
