### ISSUE TITLE
PodLogs#streamNamespacedPodLog stops tailing logs after 5 mins.

### ISSUE THREAD

**Issue by shrids** [kubernetes-client/java#502]
Hi,

Observing that `PodLogs#streamNamespacedPodLogs` stops tailing logs of a Pod after 5 mins.
I did try to set ApiClient timeouts to a value greater than 10 mins.

```
client.getHttpClient().setReadTimeout(DEFAULT_TIMEOUT_MINUTES, TimeUnit.MINUTES);
client.getHttpClient().setWriteTimeout(DEFAULT_TIMEOUT_MINUTES, TimeUnit.MINUTES);
client.getHttpClient().setConnectTimeout(DEFAULT_TIMEOUT_MINUTES, TimeUnit.MINUTES);
```

This did not fix the issue. Also, after 5 mins there isn't a way to detect that the no data is being received on the inputstream returned by PodLogs.

Any pointers on the best way to solve this would be super helpful.

**Environment:**
- Java 8
- Kubernetes client version: 3.0.0
- Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4"}

**Comment by brendandburns** [comment]
This is really dependent on your environment. PodLogs uses an HTTP GET, depending on your networking setup between you and your cluster you may timeout somewhere in a NAT/Gateway device no matter what your local client settings are.

Hope that helps, I'm going to close this since I don't think we can fix it here in this library.  Please re-open if you need more info.

Thanks
