### ISSUE TITLE
Attach standardOutputStream not working

### ISSUE THREAD

**Issue by conblem** [kubernetes-client/java#530]
When using the Attach api with the following config
`new Attach().attach(pod, true, true)`
Reading from the standardOutputStream blocks indefinitely without returning any bytes.
The standardInputStream works as expected.

 I am using the following versions:

```
<dependency>
      <groupId>io.kubernetes</groupId>
      <artifactId>client-java</artifactId>
      <version>4.0.0</version>
      <scope>compile</scope>
</dependency>
```
AdoptOpenJDK 11.0.2
Windows 10 Pro
minikube version: v0.35.0

**Comment by brendandburns** [comment]
Is your process in the container in Kubernetes actually writing anything to `stdout`?

Does `kubectl attach ...` print output?

Also, obviously you need to copy the different streams in different threads (but I assume from your previous issue that you are already doing multiple threads)

**Comment by conblem** [comment]
[Video Example](https://streamable.com/k5vf6)
[Repo example](https://github.com/conblem/k8sattach)

**Comment by brendandburns** [comment]
Two thoughts:

What happens if you sleep for > 1 second before closing the socket. I'd wait a really long time and see if it works.

Are you sure that your process is printing to stdout? What happens if you also print out stderr in your sample code?

If you want to dig around/debug the relevant code is here:
https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java

Does the example [here](https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/AttachExample.java) work correctly for you? You'll need to change the name/namespace in the code obviously...

Thanks
