### ISSUE TITLE
Changelog for v4

### ISSUE THREAD

**Issue by davidkarlsen** [kubernetes-client/java#563]
Can you please update the changelog for v4. There seems to be some breaking changes.

**Comment by brendandburns** [comment]
Change log is here:
https://github.com/kubernetes-client/java/releases/tag/client-java-parent-4.0.0

No known breaks. What are you seeing?

**Comment by davidkarlsen** [comment]
I looked in the changelog.txt. Changes in parameters from string to boolean and some orphaning changes in delete namespace.

**Comment by brendandburns** [comment]
ah, those must be changes in the generated code. It's likely improvements in the Kubernetes swagger spec that feeds the code generator.

That's much harder to track. That's the reason that we always move to a new major version whenever we rev. the API so that people understand that there can be breaking changes.

I'll add some better documentation to explain this.
