### ISSUE TITLE
Generated code is unwieldy

### ISSUE THREAD

**Issue by jackmahoney** [kubernetes-client/java#582]
I really love kubernetes and appreciate all the work around it but is this generated java library really a respectable official client?

The first example on the README shows a method call with 9 null parameters. 

`V1PodList list = api.listPodForAllNamespaces(null, null, null, null, null, null, null, null, null);`

I know generated code with swagger makes client development easy but surely a hand written client would be better? The above example isn't idiomatic Java or good code in general.

**Comment by yue9944882** [comment]
i suppose we will apply the builder pattern to client (see existing threads at https://github.com/kubernetes-client/java/issues/409) but for now we don't a solution yet.

**Comment by brendandburns** [comment]
There are already builders, look at the example here:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/FluentExample.java

**Comment by brendandburns** [comment]
And regarding generated vs. hand written, this is a philosophic decision that was taken for all clients. The Kubernetes API is large and continuously changing.

If you hand write code, there are always gaps between the library and the latest APIs, that's a different kind of pain for users. The decision was taken because we believe that API coverage is more important than a fluent library.

And of course, in this case, we have also figured out how to generate a more fluent library as well.

Additionally, if you want to write and maintain a more fluent library on top of this lower-level client, PRs are welcome.

Closing since there's no more action items here.
