### ISSUE TITLE
[Question] Informer Error Handling

### ISSUE THREAD

**Issue by rbocanegra** [kubernetes-client/java#616]
Hi!

I am using the informer feature of the client to watch some api types. It handle some errors automatically, but in the case of an Unauthorized (401) it keeps logging `io.kubernetes.client.ApiException: Unauthorized` in a loop and I can't find a way to stop the informer in that case. The loops never ends until I stop the app.
So I was wondering if there is a way to deal with that situation already or if it should need a enhancement like an error handler callback or something else to let the user customize error handling.

Thanks!

**Comment by yue9944882** [comment]
there shouldn't be those errors in the first place i suppose. mostly the unauthorized error suggests that your informer (as a client) isn't correctly configured w/ kubeconfig or serviceaacount. please consider a fix in the client's credential. and additionally the informer from native client-go will also be retrying at an 1s-ish interval on that error instead of shutdown https://github.com/kubernetes/kubernetes/pull/77480. we'll align w/ upstream.

**Comment by brendandburns** [comment]
@yue9944882 is there more to do here? Or should we close this issue?

**Comment by rbocanegra** [comment]
You can close this issue.
