### ISSUE TITLE
Kubernetes java client always uses system:anonymous User even I set credentials

### ISSUE THREAD

**Issue by janakec19** [kubernetes-client/java#626]
Java Sample code:
ApiClient defaultClient = Configuration.getDefaultApiClient();
String credentials = new String(Base64.getEncoder().encode("username:password".getBytes()));
ApiKeyAuth basicAuth = (ApiKeyAuth) defaultClient.getAuthentication("BearerToken");
basicAuth.setApiKey(credentials);
basicAuth.setApiKeyPrefix("Basic");
defaultClient.setBasePath("https://192.168.*.*:8000");
Configuration.setDefaultApiClient(defaultClient);

**Error response:
"**apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets is forbidden: User "system:anonymous" cannot list resource

I already created role binding :
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: deployment-manager-binding
namespace: default
subjects:

kind: User
name: kubernetes-admin
namespace: default
apiGroup: rbac.authorization.k8s.io
roleRef:
kind: Role
name: deployment-manager
apiGroup: ""
Why Java client is always using system:anonymous User even i set username and password?

**Comment by yue9944882** [comment]
i replied in another thread https://github.com/kubernetes-incubator/apiserver-builder-alpha/issues/378#issuecomment-511686789

**Comment by brendandburns** [comment]
You should just load all this from a `$KUBECONFIG` file if possible.

If it's not possible, you should use the `Config.fromUserPassword()` function:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/Config.java#L55

Instead of trying to roll it yourself.

Closing since I think this question is answered, please re-open if you have further problems.
