### ISSUE TITLE
SharedInformerFactory::stopAllRegisteredInformers results in error logs

### ISSUE THREAD

**Issue by Hendrik-H** [kubernetes-client/java#656]
When trxying to do a clean shutdown of an informer using SharedInformerFactory::stopAllRegisteredInformers several errors get logged due to the code causing threads to get interrupted and that being logged as errors. I would expect the log to be on a far lower level and ideally not at all during a clean shutdown.

In library version `5.0.0` a thread is also left stuck in https://github.com/kubernetes-client/java/blob/release-5.0/util/src/main/java/io/kubernetes/client/informer/cache/Controller.java#L140
The class changed (https://github.com/kubernetes-client/java/commit/e21e04401182b0e286d0686babeb8ec3f9d6af14#diff-c8c2f9e8332c147f71d59605f08ed0c3) after the version was released but no new version is available. So I'm not sure this was fixed. From the code change I tend to believe that it is not changed as I do not see anything that would result in the `queue.pop` call to return and the thread should end up doing another `pop` call straight away. I would expect the endless loop to check some state and exit cleanly if some state is set.

In my opinion it would also be nice if background threads would be set to be daemon threads so that they don't block the JVM to exit.

**Comment by Hendrik-H** [comment]
The `interrupt` call does actually exist, it is here: https://github.com/kubernetes-client/java/blob/f1e5a0434794fb6e4813446bdcc5249bca79646a/util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java#L150
But do to the endless loop in https://github.com/kubernetes-client/java/blob/f1e5a0434794fb6e4813446bdcc5249bca79646a/util/src/main/java/io/kubernetes/client/informer/cache/Controller.java#L138 the thread goes straight back to wait and never quits.

**Comment by yue9944882** [comment]
>  I would expect the log to be on a far lower level and ideally not at all during a clean shutdown.

the thread is indeed leaking.. sending a fix to resolve that, and we're planning a new release in the next week..

/assign

**Comment by yue9944882** [comment]
closing as it's fixed

**Comment by SunithaR** [comment]
@yue9944882 I'm still seeing this issue, when using latest version 5.0.0. Is there a different version that has this fix?
        <dependency>
          <groupId>io.fabric8</groupId>
          <artifactId>kubernetes-client</artifactId>
          <version>5.0.0</version>
        </dependency>

**Comment by SunithaR** [comment]
@Hendrik-H  I facing this same issue with the latest version. Has your issue been resoved, if so how?

2021-01-27 09:40:13.217 ERROR 1 --- [pool-3-thread-1] i.f.k.c.i.cache.ProcessorListener : Processor thread interrupted: null
2021-01-27 09:40:13.218 ERROR 1 --- [-controller-Job] i.f.k.client.informers.cache.Controller : DefaultController#processLoop got interrupted null
java.lang.InterruptedException: null
at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[na:na]
at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090) ~[na:na]
at io.fabric8.kubernetes.client.informers.cache.DeltaFIFO.pop(DeltaFIFO.java:322) ~[kubernetes-client-5.0.0.jar!/:na]
at io.fabric8.kubernetes.client.informers.cache.Controller.processLoop(Controller.java:158) ~[kubernetes-client-5.0.0.jar!/:na]
at io.fabric8.kubernetes.client.informers.cache.Controller.run(Controller.java:112) ~[kubernetes-client-5.0.0.jar!/:na]
at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
2021-01-27 09:40:13.219 WARN 1 --- [//29.67.0.1/...] i.f.k.c.d.i.WatchConnectionManager : Exec Failure
javax.net.ssl.SSLException: Socket closed at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[na:na] at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321) ~[na:na] at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264) ~[na:na] at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259) ~[na:na] at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1314) ~[na:na] at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:839) ~[na:na] at okio.Okio$2.read(Okio.java:140) ~[okio-1.15.0.jar!/:na] at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[okio-1.15.0.jar!/:na] at okio.RealBufferedSource.request(RealBufferedSource.java:68) ~[okio-1.15.0.jar!/:na] at okio.RealBufferedSource.require(RealBufferedSource.java:61) ~[okio-1.15.0.jar!/:na] at okio.RealBufferedSource.readByte(RealBufferedSource.java:74) ~[okio-1.15.0.jar!/:na] at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117) ~[okhttp-3.12.12.jar!/:na] at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) ~[okhttp-3.12.12.jar!/:na] at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274) ~[okhttp-3.12.12.jar!/:na] at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214) ~[okhttp-3.12.12.jar!/:na] at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) ~[okhttp-3.12.12.jar!/:na] at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[okhttp-3.12.12.jar!/:na] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na] at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Suppressed: java.net.SocketException: Socket closed
at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113) ~[na:na]
at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150) ~[na:na]
at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81) ~[na:na]
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:352) ~[na:na]
... 18 common frames omitted
Caused by: java.net.SocketException: Socket closed

**Comment by Hendrik-H** [comment]
@SunithaR sorry, not working on the project anymore where I had this issue

**Comment by SunithaR** [comment]
ok thanks for the response @Hendrik-H

**Comment by alex00324** [comment]
Pudiste solucionar el error @SunithaR  tengo el mismo creo
