### ISSUE TITLE
How to get the status of Allocated resources through api?

### ISSUE THREAD

**Issue by udit0612** [kubernetes-client/java#717]
When i describe the nodes through kubectl command , It shows the allocated resource information

**kubectl describe nodes  nodename**

![image](https://user-images.githubusercontent.com/33015983/65739754-1205ce80-e104-11e9-8bfb-53af698991d2.png)

Can you please tell me how to get such api response along with CPU, memory and ephemeral-storage percentage ?

```
                ApiClient client = Config.defaultClient();
		Configuration.setDefaultApiClient(client);
		CoreV1Api api = new CoreV1Api();
		V1NodeList listNode = api.listNode(null, null, null, null, null, null, null, null);
		listNode.getItems().forEach(i -> System.out.println(i.getStatus().getAllocatable()));
		listNode.getItems().forEach(i -> System.out.println(i.getStatus().getCapacity()));

```
I alredy tried these options but can't ge the  cpu and memory percentage usage

I am egar to know how kubectl fetch these output .

**Comment by brendandburns** [comment]
The code in kubectl calculates that percentage by looking at the Node object, the relevant Go code is here:

https://github.com/kubernetes/kubectl/blob/master/pkg/describe/versioned/describe.go#L3032

Closing this issue because the question is answered, please use the `/reopen` command if you need to reopen the issue for further assistance.

**Comment by indreshverma** [comment]
/reopen
https://github.com/kubernetes/kubectl/blob/master/pkg/describe/versioned/describe.go#L3032
given url is not working 


![Screenshot from 2024-08-29 03-04-42](https://github.com/user-attachments/assets/3b0cf0e8-1f97-4c0c-bdd3-c1dc653e16ec)
