### ISSUE TITLE
To do comment in copyDirectoryFromPod utility method of Copy class

### ISSUE THREAD

**Issue by sarveshkaushal** [kubernetes-client/java#755]
There is a TODO comment in Copy class: 
// TODO: Test that 'tar' is present in the container?
What are we trying to check here? Even if the directory is empty, shouldn't we copy it to destination as empty directory?
https://github.com/kubernetes-client/java/blob/004a28ab2031c15f2d67e3cc2dd96a352aca9195/util/src/main/java/io/kubernetes/client/Copy.java#L114

**Comment by brendandburns** [comment]
if the `tar` executable isn't present in the remote container, the command we're going to use won't work.

So something like running `tar --help` first and looking for errors would be a place to start. We probably don't want to always do it, since it would be expensive, we should make it optional...

**Comment by sarveshkaushal** [comment]
Thanks for help on this. I will take a look into this.

**Comment by sarveshkaushal** [comment]
Closing this.
