### ISSUE TITLE
Request Object should also include event type that triggered it

### ISSUE THREAD

**Issue by nprabala** [kubernetes-client/java#767]
Currently, the Request object in the extended module of the java client only takes in the name and namespace of the resource. You can use that to look up the particular object in a separate list, but that doesn't tell you anything about what kind of notification (ie, created, updated, or deleted) caused the request to be added to the workqueue. 

Should just be a simple addition of a new param -- maybe updating the examples section appropriately as well. Alternatively, the Request could also take in a JSON body param that has key val pairs with additional data you'd like to pass in optionally.

**Comment by yue9944882** [comment]
> that doesn't tell you anything about what kind of notification (ie, created, updated, or deleted)

to discriminate different kind of notification, you can use [InformerExample](https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/InformerExample.java). the controller is designed to reconcile the object regardless of the kinds of notification.. https://github.com/kubernetes-client/java/blob/2e95de4b83da764884b648bf085d9edf469c65e0/extended/src/main/java/io/kubernetes/client/extended/controller/reconciler/Reconciler.java#L3-L23

**Comment by brendandburns** [comment]
@yue9944882 can this be closed?

**Comment by nprabala** [comment]
@yue9944882  I understand the design, I don't totally understand the reasoning behind it. 

Kubernetes controllers are primarily for orchestration and reconciliation. In that sense, it makes sense for them to wake up whenever there is any kind of change to a resource -- that way they can make sure that everything matches the spec and is as it should be.

But why not also track the event type?  That would make this reconciler a lot more powerful. As a user, I would benefit from having more information about what kind of change has occurred so I can write better custom logic in response to it. 

It would also cut down on redundancy. Why write handlers for the informer, and logic for the Reconciler, when both are responding to the same events and I could just have it all in one? The modularity of attaching a Reconciler to a controller is also much more attractive than permanently tying event handlers to an informer. 

Thanks for the support, and I appreciate your taking the time.

**Comment by brendandburns** [comment]
I think this is a philosophic thing. Your controller really shouldn't care why. Your reconciler should only look at the object itself and take an action based on that object. Why the object ended up the way that it is shouldn't be necessary.

Controllers in Kubernetes are stateless by philosophic design. Needing to understand the type of event implies a sort of state machine that runs counter to the design of a controller.

If you want to use more of an event-driven or state machine design, then the Informer interface is a better way to integrate.

Hope that helps explain our approach. Happy to help answer more questions as necessary.

**Comment by yue9944882** [comment]
a controller should be working in a declarative way, or "final-state-oriented", so it doesnt have to read how the resource is changing over a period of time.

**Comment by nprabala** [comment]
Why does the controller have to work in a declarative or stateless paradigm? Why are controllers in Kubernetes stateless by philosophic design? I would like to better understand the reasoning for that decision.

**Comment by brendandburns** [comment]
Just to be clear:

It doesn't _have_ to be stateless. But that's the general design philosophy of the controller SDK packages for Kubernetes.

You're free to write a controller however you want to write a controller, but the SDK is opinionated about its approach.

The reason for this "final declarative state" or "stateless" design is that failure in a state-machine based controller is harder to handle correctly.

The first problem is remembering your history (e.g. "what have you done before") you need to check-point this state somewhere. This check-pointing is hard to get right because the write of the state change _and_ the action itself have to be transactional, otherwise you record that you took an action when you didn't, or you _don't_ record that you took an action when you did. This leads to lots of edge cases and bugs.

The other problem is that a state-machine can fail to represent the entire space of possible states. e.g. the state machine can be missing states, when this happens the state machine tends to fail in bad ways.

A stateless controller doesn't have these problems, as it can wake up any time, in any state, and start driving towards the goal state.

It's worth reading about [PID control](https://en.wikipedia.org/wiki/PID_controller) as it is the inspiration for much of the control approach in Kubernetes.

Hope that helps.

**Comment by brendandburns** [comment]
Closing this issue, as I think this discussion is completed. Please use the `/reopen` comment command to reopen if needed.
