### ISSUE TITLE
How to create a Job ,  similar to Deployment ，or can give me a related document?

### ISSUE THREAD

**Issue by chengfeng110** [kubernetes-client/java#789]
I want to create a Job, but I can't find a explain document.

**Comment by brendandburns** [comment]
You need to to use the `createNamespacedJob(...)` function in the `BatchV1Api` object.

See:
https://github.com/kubernetes-client/java/blob/da58401c5bc38bdeaa28a6f66d25481af4d6e994/kubernetes/docs/BatchV1Api.md

Closing since the question is answered, please use the `/reopen` command if you need further assistance.

**Comment by chengfeng110** [comment]
Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Brendan Burns"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月11日(星期一) 下午2:33
收件人:&nbsp;"kubernetes-client/java"<java@noreply.github.com&gt;;
抄送:&nbsp;"汪林"<363853532@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kubernetes-client/java] How to create a Job ,  similar to Deployment ，or can give me a related document? (#789)




You need to to use the createNamespacedJob(...) function in the BatchV1Api object.
 
See:
 https://github.com/kubernetes-client/java/blob/da58401c5bc38bdeaa28a6f66d25481af4d6e994/kubernetes/docs/BatchV1Api.md
 
Closing since the question is answered, please use the /reopen command if you need further assistance.
