### ISSUE TITLE
 I want to set these two fields, network namespaces and DNS Policy.

### ISSUE THREAD

**Issue by chengfeng110** [kubernetes-client/java#805]
![image](https://user-images.githubusercontent.com/33675286/69127581-79794280-0ae5-11ea-955a-cebfc931700f.png)

I can't find field in V1Container. who can guide me?

**Comment by brendandburns** [comment]
Those field are in `V1PodSpec`

https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1PodSpec.java#L70

Closing since the question is answered.

fwiw, the API docs are here:

https://kubernetes.io/docs/reference/

In the future it may be faster to just consult those docs.
