### ISSUE TITLE
The data structure of protobuf and bean is inconsistent. 

### ISSUE THREAD

**Issue by qtornado** [kubernetes-client/java#816]
![image](https://user-images.githubusercontent.com/5219170/69936890-0c69a200-1514-11ea-8c8e-0c3660b67142.png)
The data structure of protobuf and bean is inconsistent. 
Cannot use bean copy method

**Comment by brendandburns** [comment]
There are probably differences between the swagger spec and the proto files. (and there's definitely differences between the generated code [e.g. the way `List` objects are handled)

I wouldn't expect that generic bean copying will ever work properly here due to these differences in the code generators.

**Comment by yue9944882** [comment]
the proto client seems havent been re-generated for quite a period of time. indeed it can be inconsistent w/ swagger specs..

**Comment by qtornado** [comment]
OK. We can only deal with these inconsistencies one by one.
OK.只能逐个处理这些不一致的地方了。

**Comment by brendandburns** [comment]
Yeah, we do need to re-generate the proto code from new proto files, but despite this there will always be differences.
