### ISSUE TITLE
How to get cluster's metrics such as Memory, CPU ?

### ISSUE THREAD

**Issue by xingtanzjr** [kubernetes-client/java#859]
Hi,

I'd like to fetch the cluster's metrics such as Memory,CPU but it seems that the Java client doesn't contains any method for that. 

It seems that I can use `Kubectl` to fetch the metrics of all nodes just using

```
kubectl describe nodes
```

Is there some way to achieve that using Java Client ? 

Thanks!

**Comment by brendandburns** [comment]
`kubectl describe` is not a single API call, it's actually a fairly complicated piece of code.

A similar question was asked in https://github.com/kubernetes-client/java/issues/717 which also has pointers to the relevant code for `describe` and some hints about how to implement something similar in Java code.

If you create a utility class to do this, we'd welcome a PR.

Closing this issue, since the question is answered, feel free to use the `/reopen` command to reopen as needed.
