### ISSUE TITLE
CustomObjectsApi.patchNamespacedCustomObjectCall: now always selects "json-patch+json" as ContentType. Please make contentType configurable.

### ISSUE THREAD

**Issue by ekovacs** [kubernetes-client/java#866]
Since 7.0.0 (more specifically https://github.com/kubernetes-client/java/commit/dc180f9de18684195e3a399c0c2df0e33a6d2742)

in `io.kubernetes.client.openapi.apis.CustomObjectsApi.patchNamespacedCustomObjectCall(String, String, String, String, String, Object, ApiCallback)`
a new contentType was introduced:
` "application/json-patch+json"` 
It was added to localVarContentTypes array, at the 0-th. index.

Which caused it to become the only possible patching type that could be selected for a patching request, as the first element is selected from this array always.

This results in calls (that were depending on ContentType: `application/merge-patch+json`) ending up as 400, BAD Request.

Please introduce a new parameter for the method e.g.: `String patchType`, so that the user could specify which type of patch mechanism they want to use. 
When that optional argument is not specified, the current selection could be sufficient (which is: `localVarApiClient.selectHeaderContentType(localVarContentTypes)`).

This would be in line with `kubectl patch`, which allows for setting `--type` flag to set the desired patching type.

**Comment by brendandburns** [comment]
This must be a problem in the either the Swagger/OpenAPI JSON document from the main kubernetes project, or in the code generator. All of this code is generated by a code generator (https://github.com/OpenAPITools/openapi-generator)

In the meantime, you should be able to just update the `Content-Type` header on the `Call` object that is returned to set it to whatever you want.

Have you looked at the Patch example here:
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/PatchExample.java

**Comment by chrisryan10** [comment]
FYI: client-java-7.0.0.jar (latest published non alpha version I can find) does not seem to contain PatchUtils, btw, which is referenced in the PatchExample.java you linked.

**Comment by woowanamu** [comment]
In my case this code snippet works, but I have no assurance it works for all cases.
```kotlin
fun forceUpdateContentTypeToMergePatch(call: Call): Call {
  val originalRequest = call.request()
  val originalBody = originalRequest.body()!!

  val mergePatchType = "application/merge-patch+json"
  val newBody = RequestBody.create(MediaType.get(mergePatchType), requestBodyToString(originalBody))
  val newRequest = call.request().newBuilder()
    .header("Content-Type", mergePatchType)
    .method(originalRequest.method(), newBody)
    .build()
  return client.httpClient.newCall(newRequest)
}
```

**Comment by reaperes** [comment]
In my case this code snippet works, but I have no assurance it works for all cases.
```kotlin
fun forceUpdateContentTypeToMergePatch(call: Call): Call {
  val originalRequest = call.request()
  val originalBody = originalRequest.body()!!

  val mergePatchType = "application/merge-patch+json"
  val newBody = RequestBody.create(MediaType.get(mergePatchType), requestBodyToString(originalBody))
  val newRequest = call.request().newBuilder()
    .header("Content-Type", mergePatchType)
    .method(originalRequest.method(), newBody)
    .build()
  return client.httpClient.newCall(newRequest)
}
```

**Comment by cridam** [comment]
I m using the last 8.0.0 and there is still the issue. This breaks all the usage when migrating from earlier version of the API that handles properly "merge-patch". Besides, the current code (generated or not) is quite odd , since it will always lead to json-patch+json whatever the body pass to the 
patchClusterCustomObjectStatusCall(String group, String version, String plural, String name, Object body, ApiCallback _callback) throws ApiException
...
String[] localVarContentTypes = new String[]{"application/json-patch+json", "application/merge-patch+json"};
// the following took the first one...
        String localVarContentType = this.localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);
...

**Comment by brendandburns** [comment]
The problem here is basically that the open-api generated code doesn't really understand the patch semantics or Kubernetes custom `content-types`. The best solution is to set the content type on the `Call ` yourself as shown in the comment [above](https://github.com/kubernetes-client/java/issues/866#issuecomment-612362719)
