### ISSUE TITLE
list all customObjects fro  all namespaces

### ISSUE THREAD

**Issue by WywTed** [kubernetes-client/java#941]
How can i list all customObjects fro  all namespaces if the customObject's scope is namespace.
I just see the api customObjectsApi.listNamespacedCustomObject ;
For service, we can use 'coreV1Api.listServiceForAllNamespaces'
Thanks to reply.

**Comment by brendandburns** [comment]
Unfortunately the definition for that isn't in the openapi spec that is used to generate the client.

It needs to be added here:
https://github.com/kubernetes-client/gen/blob/master/openapi/custom_objects_spec.json

And then have the client regenerated.

**Comment by WywTed** [comment]
![image](https://user-images.githubusercontent.com/12699301/80910065-9cc83f00-8d5f-11ea-86e3-d07fe1e71161.png)

How to add it to the json file?
there is already the key "/apis/{group}/{version}/{plural}", so how can i add a method named "listCustomObjectForAllNamespaces" ?
does the method "get" support an array input.

**Comment by WywTed** [comment]
by the way,
is there an auto generator tool to generate java model from crd?

**Comment by brendandburns** [comment]
The full kubernetes swagger is here:

https://github.com/kubernetes-client/java/issues/941#issuecomment-623078707

If you search for `forAllNamespaces` you'll see some examples.

There is a very alpha level tool for generating Java from CRDs documented here:

https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md

We're working on making it more official/complete.

See the issue here:
https://github.com/kubernetes-client/java/issues/921

**Comment by davidxia** [comment]
Using `listClusterCustomObject()` worked for me even though my custom resource is namespace scoped.

**Comment by davidxia** [comment]
@brendandburns I have the same question as @huhu-sky if you have any ideas.

> How to add it to the json file?
> there is already the key "/apis/{group}/{version}/{plural}", so how can i add a method named "listCustomObjectForAllNamespaces" ?
does the method "get" support an array input.

I created this issue and restated the problem here https://github.com/kubernetes-client/gen/issues/268#issuecomment-2351625131. Basically, custom_objects_api already has a `get` for the non-namespaced API path with the name of `list_cluster_custom_object`. So it doesn't seem to allow generating another method named `list_custom_object_for_all_namespaces` for the same method and path.
