### ISSUE TITLE
Provide a JSON serializer/deserializer for AdmissionReview

### ISSUE THREAD

**Issue by vroyer** [kubernetes-client/java#971]
In order to setup a webhook admission endpoint, could you provide a JSON serializer/deserializer for AdmissionReview. The current implementation of AdmissionReview cannot be used with jaskson to implement an admission hook.

**Comment by yue9944882** [comment]
it depends on https://github.com/kubernetes/kubernetes/issues/84081

**Comment by brendandburns** [comment]
You mention Jackson, is this actually an error for the Fabric8 client? This library uses GSON for serialization.

**Comment by brendandburns** [comment]
Closing this issue, since I don't think there is more that can be done, and it will happen automatically if the kubernetes issue is resolved. Please use the `/reopen` bot command if you need further assistance.

**Comment by vroyer** [comment]
To implement a validation wehook endpoint in the micronaut framework, we need a jackson serializer/deserializer for the AdminssionReview object. The farbric8 has such serializer, but not the k8s java client. Could you provide a generated jackson serializer for such usage ?

**Comment by brendandburns** [comment]
This library uses GSON rather than Jackson and it also uses code generation, so we don't hand-write code like this. So I don't think this is something that we can do. Once Kubernetes has the object in its OpenAPI specification, the object for GSON will get automatically generated and be available.

Note that you can always write your own GSON object and use the client's GSON implementation to serialize/deserialize similar to the example here:

https://github.com/kubernetes-client/java/blob/cbc1d385dfa02da38e07e4b22498971b7b464680/examples/src/main/java/io/kubernetes/client/examples/ParseExample.java#L44

Just to summarize, I don't think we will do anything here until the Kubernetes upstream openapi specification is updated, and I don't think it's within scope to do anything for Jackson.

**Comment by vroyer** [comment]
Yes, Fabric8 code is also generated, and because the AdminssionReview include a lots of other object, it's not possible to write a GSON to Jackson serializer manually. So i guest i have to switch to the fabric8 client ...
